Cloud-Code-AI/kaizen

- README.md
> fix: readme email fix

- api/github_helper/utils.py
- api/main.py
Added github signature functionality.
> feat: Added github signature check for app

- cloudcode/llms/prompts.py
Moved information of prompt to bottom for better response.
> fix: Moved information to bottom of prompt

- api/github_helper/pull_requests.py
This pull request aims to address the issue of regenerating the access_token for every step in the process_pull_request and process_pr_desc functions.
- Added the generation of access_token using get_installation_access_token function in both process_pull_request and process_pr_desc functions.
The changes were made to ensure that a new access_token is obtained for each step, enhancing security and access control.
- It's important to ensure that the get_installation_access_token function handles error scenarios and provides appropriate error handling to avoid any potential issues with access_token generation.
- Consider adding comments or documentation to explain the purpose and usage of the access_token generation.
-- Generated with love by Cloud Code AI
<details>
<summary>Original …
> fix: Regenerating access_token for every step.

- api/main.py
- config.json
This pull request aims to address two main changes:
1. The addition of configuration-based automatic pull request (PR) generation and editing of PR descriptions.
2. The introduction of new configuration options in the `config.json` file to enable/disable auto PR review and PR description editing.
- In the `main.py` file, the code has been modified to utilize the new configuration options for auto PR review and PR description editing.
- The `config.json` file has been updated to include the new configuration options for auto PR review and PR description editing.
The changes have been made to provide more flexibility and control over the PR handling process. By introducing configuration-based settings, the codebase becomes more adaptable to different workflows and requirements. This allows …
> fix: added pr desc and pr_review in config

- cloudcode/helpers/output.py
- tests/helpers/test_output.py
This pull request introduces a new feature for merging topics in the output of code review feedback. The main changes involve refactoring the `create_pr_review_from_json` function to merge reviews based on their topics and generate a more organized markdown output. Additionally, a new `merge_topics` function has been added to facilitate the topic merging process.
The motivation behind these changes is to improve the readability and organization of code review feedback by grouping reviews based on their topics. This will make it easier for reviewers to navigate and understand the feedback provided. The refactoring also aims to enhance maintainability and extensibility of the codebase by introducing a separate function for topic merging.
-- Generated with love by Cloud Code AI
<details> …
> feat: Merging topics for single view

- cloudcode/actions/ui_tests.py
- cloudcode/helpers/output.py
- cloudcode/helpers/parser.py
- cloudcode/llms/prompts.py
- poetry.lock
- pyproject.toml
@sauravpanda using playwright now to scrape web data. Also changed test code generation to playwright instead of cypress.
> 50 integrate playwright with UI testing

- Dockerfile
- api/main.py
- cloudcode/actions/ui_tests.py
- cloudcode/playwright/.gitignore
- cloudcode/playwright/helper.py
- cloudcode/playwright/package-lock.json
- cloudcode/playwright/package.json
- cloudcode/playwright/playwright.config.js
This pull request introduces changes related to running Playwright tests within the project. The changes include modifications to the Dockerfile to install Node.js and npm, addition of new API endpoints for running UI tests, creation of new Playwright-related files and directories, and implementation of Playwright test execution logic.
1. Dockerfile: Added installation of Node.js and npm.
2. main.py: Added new API endpoint for running UI tests.
3. ui_tests.py: Added import of Playwright helper and subprocess for running tests.
4. Added new files: .gitignore, helper.py, package-lock.json, package.json, playwright.config.js.
The changes aim to enable the execution of UI tests using Playwright, providing a mechanism to run and manage UI tests through the API. This enhancement allows for …
> 54 run playwright tests

- examples/basic/generate.py
- poetry.lock
- proctai/generator/ui.py
- proctai/llms/prompts.py
- pyproject.toml
This pull request introduces changes aimed at emphasizing the importance of tests within the codebase.
- Updated import statements in `generate.py` and `ui.py` to reflect the new package structure.
- Added a new feature to store test files in JSON format in the specified folder path within `ui.py`.
- Modified the `prompts.py` file to include the 'importance' field in the JSON output.
- Updated the `pyproject.toml` file to include the new dependency on pip version 24.0.
The changes aim to improve the testing process by emphasizing the importance of tests and enhancing the test file storage mechanism. Additionally, the inclusion of the 'importance' field in the JSON output provides a clearer understanding of the test's significance. The update to the `pyproject.toml` file ensures …
> feat: added importance of tests

- .gitignore
- README.md
- kaizen/generator/ui.py
This pull request includes several changes:
1. Updated the project name from 'CloudCode' to 'Kaizen' throughout the codebase and documentation.
2. Added a new feature 'Kaizen' under the 'Features' section in the README.md.
3. Updated file structure references from 'cloudcode' to 'kaizen'.
4. Added instructions for generating tests for the website in the README.md.
5. Updated the path for storing tests files in the 'ui.py' file.
The changes aim to rebrand the project from 'CloudCode' to 'Kaizen' and incorporate the new 'Kaizen' feature. Additionally, the file structure references and test generation instructions have been updated to align with the rebranding.
-- Generated with love by Cloud Code AI
<details>
None
</details>
> fix: Updated readme

- .gitignore
- README.md
- examples/basic/execute.py
- kaizen/generator/ui.py
- kaizen/llms/prompts.py
This pull request includes updates to the README file and the addition of a new test file name generation feature.
- Updated references from 'CloudCode' to 'Kaizen' throughout the README file.
- Added a new test file name generation feature in the 'kaizen/generator/ui.py' file.
The changes aim to rebrand the project from 'CloudCode' to 'Kaizen' and introduce a new feature for generating test file names based on test names in the UI module. These updates align the project with its new branding and enhance the testing capabilities.
-- Generated with love by Cloud Code AI
<details>
None
</details>
> fix: updated readme and added test file name generation

- kaizen/helpers/output.py
- kaizen/llms/prompts.py
- Updated prompt for code review
- added functionality to remove comments and styles from html
> 76 add more info for generated code reviews

- pyproject.toml
This pull request aims to add work summary reporting functionality to the project.
- Added 'kaizen' package to the project dependencies in pyproject.toml
The addition of the 'kaizen' package is essential for implementing the work summary reporting functionality. This package likely contains the necessary tools or libraries required for generating and presenting work summaries. The update to the pyproject.toml file ensures that the project includes the required dependencies for this new feature.
-- Generated with love by Kaizen
<details>
None
</details>
> 92 add work summary reporting functionality

- examples/basic/generate.py
- examples/work_summarizer/main.py
- github_app/github_helper/pull_requests.py
- kaizen/generator/ui.py
- kaizen/helpers/general.py
- kaizen/llms/provider.py
- kaizen/reviewer/code_review.py
- kaizen/reviewer/work_summarizer.py
- kaizen/utils/config.py
- pyproject.toml
- tests/actions/test_review.py
- tests/helpers/test_output.py
This pull request introduces changes to improve the usage count feature and enhance the code review process.
- Added usage count feature to track usage across various modules and tests.
- Refactored code in multiple files to update usage count and improve code readability.
- Updated version to 0.1.3 in pyproject.toml.
The changes aim to provide better insights into the usage of different modules and tests, enabling more efficient code reviews and enhancing the overall development workflow. Additionally, the version update reflects ongoing development progress and improvements.
-- Generated with love by Kaizen
<details>
None
</details>
> feat: added usage count

- pyproject.toml
This pull request aims to update the version number in the pyproject.toml file from 0.1.9 to 0.1.10 for the 'kaizen-cloudcode' project. No significant modifications, refactoring, or new features are introduced in this change.
<details>
None
</details>
> 130 add spacing in code review response formation

- kaizen/helpers/output.py
The pull request titled 'fix: reformatted the prompt output' aims to address a formatting issue in the output template within the `output.py` file. 
The main purpose of these changes is to improve the readability and structure of the output template in the `output.py` file. The significant modifications include reformatting the collapsible template in the `PR_COLLAPSIBLE_TEMPLATE` section. Specifically, it involves adjusting the summary and potential solution sections for better alignment and clarity. The diff shows the changes made to the collapsible template, enhancing the presentation of the confidence, comment, and potential solution sections.
<details>
None
</details>
> fix: reformatted the prompt output

- README.md
- config.json
- kaizen/generator/ui.py
- kaizen/llms/provider.py
- pyproject.toml
The pull request introduces a custom model selection feature, allowing users to specify and utilize their preferred language models for generating UI tests. Significant modifications include adding custom model configurations to config.json, updating the UI test generator to support custom models, and modifying the LLM provider to handle custom model options. Additionally, the version in pyproject.toml has been updated to 0.2.0.
<details>
None
</details>
> feat: Added custom model selection

- examples/basic/generate.py
- kaizen/helpers/output.py
- kaizen/llms/prompts.py
This pull request aims to update the prompts and improve the clarity and accuracy for generating UI tests. Significant modifications include:
- Updated the prompts for UI test generation to provide clearer and more comprehensive instructions.
- Added handling for generating UI tests, including displaying progress and error handling. 
- Modified code within the 'output.py' file to include additional information in the test files.
- Refactored the prompts in 'llms/prompts.py' for improved readability and clarity.
These changes intend to enhance the user experience and streamline the process of generating UI tests. The updates reflect a focus on providing clear and accurate instructions while also improving error handling and code organization.
<details> …
> feat: Updated prompt for ui test generation

- pyproject.toml
Updated poetry version from 0.2.0 to 0.2.1 in pyproject.toml file
<details>
None
</details>
> fix: updated poetry version

- pyproject.toml
Bump poetry version from 0.2.1 to 0.2.2 in pyproject.toml file
<details>
None
</details>
> updated poetry version

- kaizen/helpers/parser.py
Updated regex in parser.py for JSON cleanup
The pull request aims to improve the JSON cleanup process by updating the regular expressions used in the `parser.py` file. The changes include:
- Updated regex patterns for JSON cleanup
- Replaced regex patterns to ensure proper handling of curly braces, square brackets, and line breaks within JSON data
<details>
None
</details>
> fix: updated json cleanup regex

- .github/workflows/build-docker.yml
- README.md
- docker-compose.yml
Added Docker image details to the project, along with a Docker Compose file and a GitHub Actions workflow.
- Added `.github/workflows/build-docker.yml` file which defines the workflow to build the Docker image and push it to Docker Hub on a release.
- Added a Docker badge to the README file, showing the number of pulls for the Docker image.
- Added a section in the README file mentioning the location of the Docker image.
- Added a `docker-compose.yml` file to facilitate deploying the API using Docker Compose.
- Modified the `image` attribute in the `docker-compose.yml` file to use the latest version of the Docker image.
Please review the changes for any potential issues or improvements.
<details>
None
</details>
> feat: Added docker image details

- pyproject.toml
Updated poetry version from 0.2.4 to 0.2.5 in pyproject.toml file.
- Changed the version from 0.2.4 to 0.2.5 in the poetry configuration
- Updated the description of the project in pyproject.toml
- Minor metadata modifications regarding authors and license
<details>
None
</details>
> updated poerty version

- kaizen/llms/prompts/work_summary_prompts.py
- kaizen/reviewer/work_summarizer.py
Updated the work summary flow for generating user-friendly summaries of git diffs for non-technical stakeholders.
- Refactored `work_summary_prompts.py`:
- Updated the `WORK_SUMMARY_SYSTEM_PROMPT` and `WORK_SUMMARY_PROMPT` strings for clearer instructions.
- Added an OUTPUT format for the work summary.
- Guidelines are now clearly defined for providing summaries.
- Modified `work_summarizer.py`:
- Added an import statement for `parser`.
- Updated the `generate_work_summaries` function:
- Now appends the extracted JSON response using `parser.extract_json`.
- Improved handling of file diffs processing.
- Utilized `parser.extract_json` to process chat completion responses.
Improvements:
- Clarify the purpose of `kaizen.helpers.parser`.
- Ensure consistent usage of formatting and syntax …
> updated work summary flow

- kaizen/llms/prompts/code_review_prompts.py
Updated the prompt formatting.
- Updated the prompt formatting for code review purposes.
- Fixed the provided `diff` section by formatting it correctly.
- Adhered to the provided guidelines for generating the PR description in JSON format.
- Made sure to follow best practices, focusing on clarity and readability in the code review process.
<details>
None
</details>
> fix: updated the prompt formatting

- pyproject.toml
Updated poetry version for bug fix
This pull request updates the version of the `tool.poetry` package used in the project.
- Change in version from `0.2.10` to `0.2.11`
- This fixes a bug that was present in the previous version
<details>
None
</details>
> updated poetry version for bug fix

- kaizen/reviewer/code_review.py
- pyproject.toml
Fixed review evaluation issue in the code review process.
- The pull request is a bugfix that addresses an issue in the review evaluation process.
- The main change is the replacement of `PR_DESC_EVALUATION_PROMPT` with `PR_REVIEW_EVALUATION_PROMPT` in the `review_pull_request` function.
- No new features were introduced.
- The refactoring primarily involves updating the prompt used for review evaluation.
- This pull request does not significantly impact performance, as the changes are focused on fixing the review evaluation issue.
- The code change improves the maintainability and readability of the code by using a more appropriate prompt for review evaluation.
<details>
None
</details>
> bugfix: fixed review evaluation issue

- examples/work_summarizer/main.py
- kaizen/helpers/parser.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/llms/prompts/work_summary_prompts.py
- kaizen/reviewer/code_review.py
- kaizen/reviewer/work_summarizer.py
Code improvements and best practices feedback for a pull request
- The new methods `generate_twitter_post` and `generate_linkedin_post` should be unit tested. Consider adding unit tests to ensure the methods function as expected.
- The `extract_markdown_content` utility function may benefit from additional error handling. Add checks for the edge cases when the input text does not match the expected format.
- In the `generate_work_summaries`, `generate_twitter_post`, and `generate_linkedin_post` methods, make sure to handle exceptions when calling `self.provider.chat_completion`. Proper exception handling will prevent the application from crashing during unexpected failures.
- Ensure that all new functions, classes, and constants have relevant comments and documentation. This will improve …
> Added social media post generator for work summarizer

- README.md
- docs/pages/_meta.json
- docs/pages/cloud_platform/_meta.json
- docs/pages/cloud_platform/getting_started.mdx
Pull request to fix and update README with additional information and better organization.
- Updated README to improve readability and provide clearer information.
- Modified file structure and added new sections to make it more organized.
- Removed unnecessary blank lines to enhance compactness.
- Provided separate sections for features, cloud platform, getting started, and project structure.
- Added details about the self-hosted GitHub app setup and the Kaizen Cloud platform.
- Added a new page for the cloud platform in the documentation.
- Reworked the contributing instructions for better clarity.
- Added a contact section and updated the license information.
- Updated the title to be more concise and descriptive.
- Moved badges and links into a single line to reduce visual noise.
- …
> fix: added more info in readme

- examples/work_summarizer/main.py
- github_app/github_helper/pull_requests.py
- kaizen/generator/pr_description.py
- kaizen/helpers/output.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/llms/provider.py
- kaizen/reviewer/code_review.py
- pyproject.toml
- tests/actions/diff_pr_test.py
<Brief one-line summary of the pull request>: This pull request introduces changes related to generating pull request descriptions, processing pull request files based on their content, and creating review comments.
<Detailed multi-line description in markdown format>
- Introduces a new `PRDescriptionGenerator` class in `kaizen/generator/pr_description.py` for generating pull request descriptions.
- Modifies `github_app/github_helper/pull_requests.py` by importing new dependencies from `kaizen.generator.pr_description` and `kaizen.helpers.output` and initializing the `CodeReviewer` class with an `LLMProvider` instance.
- Modifies `kaizen/reviewer/code_review.py` to import the `create_pr_review_text` function from `kaizen.helpers.output` and remove unnecessary imports.
- Modifies the …
> 255 for pr for files based on

- docs/pages/self_hosting_guide/_meta.json
- docs/pages/self_hosting_guide/using_azure_openai_with_kaizen.mdx
Added detailed documentation on integrating Azure OpenAI with Kaizen.
This pull request provides a comprehensive guide on integrating Azure OpenAI with Kaizen. The documentation covers the necessary steps to set up the environment variables and update the `config.json` file for successful integration.
List of key changes:
- Added a new entry `using_azure_openai_with_kaizen` in `_meta.json` file for the new documentation page.
- Added a new file `using_azure_openai_with_kaizen.mdx` containing the detailed documentation on integrating Azure OpenAI with Kaizen.
- Outlines the steps to set environment variables for Azure OpenAI authentication and interaction.
- Describes model configuration updates required in the `config.json` file for Azure OpenAI deployment.
- Concludes with a summary of …
> Added more info on how to use different llm providers

- docs/pages/self_hosting_guide/using_azure_openai_with_kaizen.mdx
Fix: Removed unnecessary lines from Azure OpenAI integration guide.
- The pull request aims to remove unnecessary lines from the Azure OpenAI integration guide for Kaizen.
- The changes focus on removing the Conclusion section, which was deemed not required.
- No new features or refactoring are introduced in this pull request.
- The main purpose of this pull request is to improve the readability and maintainability of the documentation by removing redundant content.
<details>
None
</details>
> fix: removed unnecessary lines

- kaizen/llms/provider.py
- pyproject.toml
Fixes asynchronous call delay in the chat completion function.
- The pull request aims to address an issue with asynchronous calls in the `chat_completion` function, which was causing a delay in response time.
- The change replaces the previous workaround using `asyncio.get_event_loop().run_until_complete()` with a direct call to the `self.provider.completion` method.
- This modification is expected to improve the performance and reduce the delay in completing the chat routing.
- The code modification is minimal and focused on promoting better error handling, readability, and maintainability.
- The `pyproject.toml` file has also been updated to reflect the version change to `0.3.1`.
<details>
None
</details>
> fix: changed the router call to sync completion

- .github/workflows/ pypi-publish-cli.yml
Updated GitHub workflow path for CLI.
- Updated the CI/CD GitHub workflow configuration to include triggering on pushes to paths related to the CLI feature.
- The changes help the workflow to be more specific and only run when modifications are made to the CLI related codebase, which can be beneficial for maintaining performance and isolating build issues.
<details>
None
</details>
> updated github workflow path for cli

- kaizen/generator/pr_description.py
- kaizen/generator/unit_test.py
- kaizen/llms/prompts/unit_tests_prompts.py
- kaizen/llms/provider.py
- kaizen/parsers/__init__.py
- kaizen/parsers/javascriptparser.py
- kaizen/parsers/pythonparser.py
- kaizen/parsers/reactparser.py
- kaizen/parsers/reacttsparser.py
- kaizen/parsers/typescriptparser.py
- pyproject.toml
Added basic unit test generation feature to the codebase.
In this pull request, a new feature for generating basic unit tests has been introduced. The main changes include the addition of a new module `unit_test.py`, which contains the `UnitTestGenerator` class responsible for generating unit tests for various programming languages.
Additionally, two new files `unit_tests_prompts.py` and `typescriptparser.py` have been added to the `kaizen/llms/prompts` and `kaizen/parsers` directories, respectively. These files contain the necessary code to handle the unit test generation for multiple languages, including TypeScript.
The `UnitTestGenerator` class supports Python, JavaScript, TypeScript, and React applications and follows best practices for generating unit tests in each language. The …
> feat: added basic unit test generation

- kaizen/generator/pr_description.py
- kaizen/helpers/output.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/reviewer/code_review.py
Added a new field for code solution in the pull request description generator.
- Added a new field `fixed_code` in the code review prompts to generate the fixed code script to replace the commented line.
- Updated the `review_pull_request` function to raise an exception when both `diff_text` and `pull_request_files` are empty.
- Updated the `generate_pull_request_desc` function to raise an exception when both `diff_text` and `pull_request_files` are empty.
- Updated the `create_pr_review_text` function to format the markdown output for high-ranked issues.
<details>
None
</details>
> feat: added one more field for code solution

- examples/code_review/main.py
- github_app/github_helper/pull_requests.py
- github_app/github_helper/utils.py
Added an example to demonstrate code review functionality.
- Added a new file `main.py` in the `examples/code_review` directory.
- The `main.py` file contains a code review example using the `CodeReviewer` class from the `kaizen.reviewer.code_review` module.
- The example demonstrates how to use the `CodeReviewer` class to review a pull request, generate a review description, and create review comments.
- The `github_app/github_helper/pull_requests.py` file has been updated to import the `get_pr_files` function from the `github_app.github_helper.utils` module.
- The `get_pr_files` function has been moved from the `github_app/github_helper/pull_requests.py` file to the `github_app/github_helper/utils.py` file.
- The `get_pr_files` function has been updated to include the `access_token` …
> 287 added example to test code review

- README.md
- kaizen/generator/pr_description.py
- kaizen/helpers/general.py
- kaizen/helpers/parser.py
- kaizen/llms/provider.py
- kaizen/reviewer/code_review.py
- kaizen/reviewer/ui_review.py
- kaizen/reviewer/work_summarizer.py
- pyproject.toml
Added retry mechanism for JSON parsing in LLM (Large Language Model) to improve robustness.
This pull request introduces a retry mechanism for JSON parsing in the LLM to handle potential parsing errors. The changes are focused on improving the robustness of the JSON parsing functionality.
**Key Changes:**
* Added a `retry` decorator in `general.py` to enable retrying failed JSON parsing attempts.
* Implemented `chat_completion_with_json` method in `provider.py` to wrap the `chat_completion` method with JSON parsing and retry logic.
* Updated `pr_description.py`, `code_review.py`, `ui_review.py`, and `work_summarizer.py` to use the new `chat_completion_with_json` method.
* Removed the `extract_json_with_llm_retry` function from `parser.py` as it is no longer needed.
**New Features:**
* …
> feat: added retry for json parsing in llm

- examples/code_review/main.py
- kaizen/generator/pr_description.py
- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request updates the logic for generating pull request descriptions.
- **Refactoring:** The `generate_pull_request_desc` method in `pr_description.py` has been refactored to handle large diffs by processing files in chunks.
- **New Feature:** The `_process_files_generator` function is introduced to iterate over files and generate descriptions for each file chunk.
- **Performance Improvement:** The code now checks for available tokens before processing each file chunk, ensuring that the LLM is not overloaded.
- **Error Handling:** The code now raises an exception if both `diff_text` and `pull_request_files` are empty.
- **Code Optimization:** The code has been optimized to reduce the number of LLM calls and improve efficiency.
- **Updated Logic:** The logic for generating …
> fix: updated merge description logic

- kaizen/generator/pr_description.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/reviewer/code_review.py
- pyproject.toml
Fixes a bug in the description generation logic.
- **Bug Fix:** The `_process_files` function was incorrectly extending the `file_descs` list with itself instead of the `file_review` list, leading to an infinite loop and incorrect description generation. This issue has been resolved by correctly extending the `file_descs` list with the `file_review` list.
- **Refactoring:** The `_process_file_chunk` function now includes a check for empty `diff_data` to prevent unnecessary processing and potential errors.
- **Improved Code Quality:** The code has been refactored to improve readability and maintainability.
<details>
None
</details>
> bugfix: description generation bug fix

- examples/code_review/main.py
- github_app/github_helper/pull_requests.py
- github_app/github_helper/utils.py
- kaizen/helpers/parser.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/reviewer/code_review.py
This pull request refines the code review evaluation prompt to focus on identifying specific code lines for review.
- **Refactored:** The `CodeReviewer` class now uses a lower default temperature (0.1) for the LLM provider, potentially improving the consistency and accuracy of code reviews.
- **Updated:** The `get_diff_text` function now uses `application/vnd.github.v3.patch` as the `Accept` header, ensuring the GitHub API returns a patch file instead of a diff file.
- **Modified:** The `EXCLUDED_FILE_TYPES` list in the `kaizen/helpers/parser.py` file has been expanded to include a wider range of file types and directory names typically excluded from code reviews. This helps improve the accuracy and efficiency of the code review process by focusing on relevant code files.
- **Added:** The …
> 309 update code review re eval prompt focused on code line identification

- examples/code_scan/main.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/llms/prompts/code_scan_prompts.py
- kaizen/llms/provider.py
- kaizen/reviewer/code_scan.py
This pull request introduces code scan functionality to the Kaizen project, including a new `CodeScanner` class to analyze code for security, performance, and quality issues.
- **New Feature:** Added `CodeScanner` class to analyze code and generate a list of issues.
- **New Feature:** Implemented `review_code` method in `CodeScanner` to process code and identify issues.
- **New Feature:** Introduced `CodeScanOutput` dataclass to encapsulate code scan results, including issues, usage statistics, model name, and cost.
- **New Feature:** Created `CODE_SCAN_SYSTEM_PROMPT` and `CODE_SCAN_PROMPT` for code scan analysis.
- **Refactoring:** Updated `LLMProvider` to handle model groups and provide usage cost information.
- **New Feature:** Added `is_code_review_prompt_within_limit` method to …
> feat: added code scan functionality

- .kaizen/unit_test/test_create_folder.py
- .kaizen/unit_test/test_create_pr_description.py
- .kaizen/unit_test/test_get_parent_folder.py
- .kaizen/unit_test/test_get_web_html.py
- examples/unittest/main.py
- kaizen/generator/unit_test.py
- pyproject.toml
This pull request introduces a custom folder structure for test output and refactors the `UnitTestGenerator` class to allow specifying a custom output folder for generated test files.
- **New Feature:** Introduces a custom folder for storing test output.
- The `create_folder` function now handles empty and `None` folder paths, raising a `ValueError` in these cases.
- Error handling for `OSError` during folder creation has been added.
- The `test_create_folder_empty_path` and `test_create_folder_none_path` tests have been updated to reflect the new `ValueError` handling.
- The `test_create_folder_os_error` test has been updated to handle the specific `OSError` message.
- **Modifications:**
- The `get_parent_folder` function now handles trailing slashes in the path.
- The …
> feat: added custom folder for test output

- cli/kaizen_cli/cli.py
- cli/pyproject.toml
This pull request adds a new unit test generation feature to the Kaizen CLI application.
- Added a new `unit_test` command to the CLI, allowing users to generate unit tests for a given file path.
- Integrated the `UnitTestGenerator` class to handle the unit test generation logic.
- Updated the `cli.py` file to include the new `unit_test` command and its associated click arguments.
- Modified the `project.toml` file to bump the Kaizen CLI version to `0.1.4`.
- This change introduces a new feature that enables users to automatically generate unit tests for their code, improving overall testing and quality assurance processes.
<details>
None
</details>
> feat: added unit test to cli

- kaizen/helpers/output.py
This pull request updates the output format for code review comments.
- **Modified `kaizen/helpers/output.py`:**
- Updated the `PR_COLLAPSIBLE_TEMPLATE` to include an empty line after the summary and before the potential solution.
- Added an empty line after the potential solution and before the code block.
- These changes improve the readability and formatting of the code review comments.
<details>
None
</details>
> fix: updated output format for code review

- examples/code_review/main.py
- kaizen/helpers/parser.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/reviewer/code_review.py
- kaizen/reviewer/work_summarizer.py
- tests/helpers/test_patch_parser.py
This pull request enhances the code review process by adding context data to the code review prompt, enabling the system to better understand and process diff or patch data.
- **Context Data:** The code review prompt now includes context data about the diff or patch, such as the file name, patch details, and line numbers. This helps the LLM understand the changes being made and provide more accurate and relevant feedback.
- The structure of the code review prompt has been updated to incorporate the new context data.
- The default temperature for the LLM provider has been set to 0.1 in the `WorkSummarizer` class to ensure more deterministic and consistent responses.
- The `_process_files_generator` function has been modified to include the new context data in the prompt. …
> 327 code review add context data to learn how to process diff or patch data

- .flake8
- examples/ask_question/main.py
- kaizen/llms/prompts/ask_question_prompts.py
- kaizen/reviewer/ask_question.py
This pull request introduces a new feature that allows users to ask questions regarding pull requests, leveraging an AI assistant to provide insights based on the code changes. The implementation includes new modules for processing questions and generating answers, enhancing the code review process.
- Key Changes:
- Added a new `ask_question` functionality that allows querying about pull requests.
- Introduced the `QuestionAnswer` class to handle question processing and interaction with the AI model.
- Implemented methods to check token limits and process questions based on full diffs or individual files.
- The ability to ask specific questions about pull requests, such as changes made, performance implications, and dependencies introduced.
- Integration with an AI model …
> feat: Ask a question functionality

- kaizen/helpers/output.py
- pyproject.toml
This pull request primarily addresses a formatting issue in the PR collapsible template within the output helper. The change enhances the readability of the summary section by removing unnecessary characters, thereby improving the overall presentation of the template.
- Removed the unnecessary arrow (`-->`) from the `<summary>` tag in the PR collapsible template to streamline the display of comments.
- No new features were introduced in this pull request.
- Updated the version number in `pyproject.toml` from `0.3.11` to `0.3.12` to reflect the changes made in this release.
<details>
None
</details>
> fix: removed --> line

- github_app/github_helper/pull_requests.py
- kaizen/helpers/output.py
- pyproject.toml
This pull request adds a link to the Kaizen website in the pull request description generated by the Kaizen tool. The purpose is to provide more context and information about the Kaizen tool for users who may not be familiar with it.
- Key Changes: Added a link to "Kaizen" in the pull request description template.
- New Features: None
- Refactoring: None
The changes were made in two files:
1. `github_app/github_helper/pull_requests.py`: The link to the Kaizen website was added to the pull request description.
2. `kaizen/helpers/output.py`: The link to the Kaizen website was also added to the pull request description template.
Additionally, the version of the Kaizen package was updated from `0.3.12` to `0.3.13` in the `pyproject.toml` file.
Overall, this pull request aims to enhance the …
> feat: added link to kaizen message

- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request introduces the ability to specify a custom LLM model for code review tasks. This enhancement provides greater flexibility and control over the model used for code analysis and feedback.
- Key Changes:
- Added `default_model` parameter to `CodeReviewer` constructor to set a default model for reviews.
- Introduced `model` parameter to `review_pull_request` function to allow overriding the default model for specific reviews.
- Modified `_process_full_diff` and `_process_file_chunk` functions to accept and use the custom model provided.
- Added support for passing a custom model during code review.
- Refactoring:
- Updated `pyproject.toml` to reflect the new version.
<details>
None …
> feat: pass custom model during code review

- kaizen/llms/prompts/code_review_prompts.py
- pyproject.toml
This pull request updates the code review prompts to focus on identifying potential issues caused by code removals and providing feedback on new code additions.
- Key Changes:
- Modified the code review prompts in `code_review_prompts.py` to emphasize the importance of analyzing removals and providing feedback on additions.
- None
- Refactoring:
- None
<details>
None
</details>
> fix: updated the code review prompts to change focus

- docs/pages/features/_meta.json
- docs/pages/features/code_scan.mdx
- docs/pages/features/unit_test.mdx
- pyproject.toml
This pull request introduces documentation for the newly implemented Code Scanner and Unit Test Generator features within the Kaizen tool. The changes aim to enhance user understanding and utilization of these features, promoting better code quality and testing practices.
- Key Changes:
- Updated the `_meta.json` file to include entries for "Unit Tests" and "Code Scan" features.
- Created a new documentation page for the Code Scanner feature, detailing its functionality, usage, benefits, and limitations.
- Created a new documentation page for the Unit Test Generator feature, outlining its operation, usage, benefits, and limitations.
- **Code Scanner**: A feature that provides static code analysis to identify potential issues and vulnerabilities in the codebase.
- **Unit …
> added doc for code review and unit test

- README.md
This pull request enhances the README file by adding a new documentation link for the Kaizen project, improving accessibility to relevant resources for users and contributors.
- Added a new badge linking to the Kaizen documentation.
- No new features introduced; however, the addition of the documentation link serves to improve user experience.
- Removed the "Project Structure" and "Contributing" sections from the README, which may have implications for clarity and guidance for potential contributors.
<details>
None
</details>
> updated the readme data

- docs/pages/contributing/code_of_conduct.mdx
- docs/pages/contributing/development_setup.mdx
- docs/pages/contributing/how_to_contribute.mdx
This pull request adds more detailed documentation on how to contribute to the Kaizen open-source project. It provides guidance on setting up the development environment, finding issues to work on, making changes, submitting pull requests, and following the project's community guidelines.
- Key Changes:
- Added a step-by-step guide for setting up the development environment, including cloning the repository, configuring environment variables, and running examples.
- Provided instructions on finding issues to work on, such as checking the project's issue tracker and looking for "good first issue" or "help wanted" labels.
- Outlined the process for making changes, including writing code, adding or updating tests, and committing changes with clear commit messages.
- Described the pull …
> doc: added more info on how to contribute

- README.md
- docs/theme.config.jsx
This pull request enhances the README.md file by adding instructions for creating and activating a virtual environment before installing Kaizen. This ensures a consistent and isolated development environment for users.
- Key Changes:
- Added separate steps for creating and activating a virtual environment on Windows and Mac/Linux systems before installing Kaizen.
- Updated the installation steps to use `poetry` for dependency management.
- Modified the test generation and execution commands to reflect the use of `poetry`.
- New Features: No new features were introduced in this pull request.
- Refactoring: No major refactoring was done in this pull request.
<details>
This pull request …
> Changes in Readme.md

- examples/code_review/main.py
- github_app/github_helper/pull_requests.py
- kaizen/helpers/output.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/reviewer/code_review.py
This pull request introduces a new feature that checks for modifications to sensitive files in pull requests. It enhances the code review process by identifying files that may contain sensitive information, thereby improving security and compliance.
- Key Changes:
- Added a `check_sensitive_files` method to identify changes made to sensitive files based on predefined patterns.
- Introduced a dictionary `sensitive_files` that categorizes sensitive file types into various groups (e.g., Configuration, Build and Dependency, Security).
- Updated the `review_pull_request` method to include the results from the sensitive files check in the review output.
- Implementation of a comprehensive check for sensitive files, which generates alerts for changes made to files that match the …
> feat: added a check for sensetive files

- docs/pages/features/unit_test.mdx
- examples/unittest/main.py
- kaizen/actors/unit_test_runner.py
- kaizen/generator/unit_test.py
- kaizen/parsers/rustparser.py
- pyproject.toml
This pull request introduces significant changes to the Unit Test Generator feature in the Kaizen project. The main enhancements include the ability to execute generated unit tests and comprehensive reporting of the results, improving the overall usability and functionality of the testing framework.
- Added the capability to execute generated unit tests and report the results.
- Integrated a new `UnitTestRunner` class to discover and run unit tests for various programming languages, including Python, JavaScript, TypeScript, React, and Rust.
- Implemented detailed reporting of test results, including the number of tests run, failures, and errors.
- Added support for additional file extensions such as `.jsx`, `.tsx`, and `.rs` to accommodate a wider range of project types. …
> feat: added method to execute the unit tests

- README.md
- docs/pages/contributing/_meta.json
- docs/pages/contributing/setting_various_llms.mdx
This pull request adds a new section to the contributing documentation, providing guidance on how to set up various language models (LLMs) in the `config.json` file. This allows contributors to configure different LLM providers and models for use in the Kaizen project.
- Key Changes:
- Added a new page `setting_various_llms.mdx` in the `docs/pages/contributing/` directory.
- Documented the structure of the `config.json` file and the required configurations for different LLM providers, including:
- OpenAI models
- Azure OpenAI models
- GroQ models
- New Features: None
- Refactoring: None
The new documentation covers the following key points:
1. **Basic Setup**: Explains the overall structure of the `config.json` file and the `language_model` configuration object.
2. **Example: OpenAI …
> doc: added info on how to setup llm info

- kaizen/llms/prompts/unit_tests_prompts.py
This pull request aims to enhance the existing unit test prompts used by the language model to include Rust-specific instructions and guidelines. The goal is to provide more comprehensive support for generating high-quality unit tests across a wider range of programming languages, including Rust.
- Key Changes:
- Added Rust as a supported programming language in the `UNIT_TEST_SYSTEM_PROMPT`.
- Included Rust-specific instructions in the `UNIT_TEST_PROMPT` and `UNIT_TEST_REVIEW_PROMPT`, specifying the use of `#[test]` for test functions and `#[cfg(test)]` for test modules.
- New Features: None
- Refactoring: None
<details>
None
</details>
> enh: Modify LLM prompts to add rust-specific instructions for unit tests

- .kaizen/unit_test/kaizen/helpers/test_create_folder.py
- .kaizen/unit_test/kaizen/helpers/test_create_pr_description.py
- .kaizen/unit_test/kaizen/helpers/test_create_pr_review_text.py
- .kaizen/unit_test/kaizen/helpers/test_create_test_files.py
- .kaizen/unit_test/kaizen/helpers/test_get_parent_folder.py
- .kaizen/unit_test/kaizen/helpers/test_get_web_html.py
- examples/unittest/main.py
- kaizen/generator/e2e_tests.py
- kaizen/generator/unit_test.py
- kaizen/llms/prompts/e2e_tests_prompts.py
- poetry.lock
- pyproject.toml
This set of pull requests introduces significant improvements to the test case generation functionality, enhances user experience through visual feedback, and refines the overall code structure for better maintainability and readability.
- Added `tqdm` library to enhance the E2E test generation process, providing users with real-time progress feedback.
- The `create_pr_description` function now supports handling special characters and generates more visually appealing PR descriptions with collapsible sections.
- Introduced additional test cases to cover various input scenarios, including normal cases, edge cases, and boundary conditions.
- Refactoring:
- Refactored the `create_pr_description` function to gracefully handle special characters, empty strings, and long …
> feat: add tqdm for pretty printing the test case generation

- kaizen/generator/unit_test.py
This pull request extends the functionality of the `UnitTestGenerator` class to support generating unit tests from directories, in addition to individual files. This enhancement allows the generator to recursively process all source files within a specified directory and generate corresponding unit tests.
- Key Changes:
- Added a new method `generate_tests_from_dir` that takes a directory path as input and generates tests for all source files within that directory and its subdirectories.
- The `generate_tests` method now supports an optional `output_path` parameter to specify the output directory for the generated test files.
- Refactored the `generate_test_files` method to improve readability and maintainability.
- The `UnitTestGenerator` can now generate unit tests for …
> feat: Extend `UnitTestGenerator` to support test generation from directories

- docs/pages/features/unit_test.mdx
This pull request updates the documentation for the `UnitTestGenerator` class to include information about the new `generate_tests_from_dir` method. This method allows users to generate unit tests for all files in a given directory, simplifying the process of creating comprehensive test suites.
- Key Changes:
- Added documentation for the `generate_tests_from_dir` method, which generates unit tests for all files in a specified directory.
- Expanded the overview section to mention the new directory-based test generation feature.
- `generate_tests_from_dir` method to generate unit tests for all files in a directory.
- Refactoring:
- No major refactoring changes included in this pull request.
<details> …
> doc: add doc for unit test generation from directory

- kaizen/reviewer/code_review.py
This pull request aims to enhance the code review process by introducing several key improvements. The changes focus on identifying and handling sensitive files, improving the review summary generation, and optimizing the usage cost calculation.
- Key Changes:
- Renamed the `check_sensetive_files` function to `check_sensitive_files` to fix a typo.
- Updated the comment in the `check_sensitive_files` function to use the correct spelling of "sensitive".
- Refactoring:
- Improved the `_merge_topics` function to consolidate review topics and their associated data.
- Optimized the usage cost calculation by introducing the `get_usage_cost` method in the provider.
- Added the ability to check for changes made to sensitive files during the code review process.
- The `check_sensitive_files` …
> fix: Typo fix in sensitive file check

- .kaizen/unit_test/kaizen/helpers/test_create_folder.py
- .kaizen/unit_test/kaizen/helpers/test_create_pr_description.py
- .kaizen/unit_test/kaizen/helpers/test_create_pr_review_text.py
- .kaizen/unit_test/kaizen/helpers/test_create_test_files.py
- .kaizen/unit_test/kaizen/helpers/test_get_parent_folder.py
- .kaizen/unit_test/kaizen/helpers/test_get_web_html.py
- config.json
- examples/code_scan/main.py
- kaizen/generator/unit_test.py
- kaizen/helpers/patterns.py
- kaizen/llms/prompts/code_scan_prompts.py
- kaizen/reviewer/code_scan.py
- pyproject.toml
This pull request focuses on refactoring the unit tests for the `create_folder` function in the `kaizen.helpers` module. The changes primarily aim to improve the readability and consistency of the test code, ensuring better maintainability and clarity for future developers.
- None
- Standardized the use of double quotes for string literals across the test files.
- Reformatted function definitions to enhance readability by aligning parameters vertically.
- Improved overall readability of the test cases by adjusting formatting and structure.
- Enhanced clarity of mock assertions by ensuring consistent string formatting in debug messages.
- Removed unnecessary whitespace and ensured proper spacing around code blocks for better visual separation.
- Other …
> feat: updated code scan with re eval

- .kaizen/unit_test/examples/unittest/typescript_code/test_homepage.tsx
- config.json
- examples/unittest/typescript_code/home.page.tsx
- examples/unittest/typescript_unittest.py
- kaizen/generator/unit_test.py
- kaizen/parsers/typescriptparser.py
- pyproject.toml
This pull request introduces a comprehensive set of unit tests for the `HomePage` component in a TypeScript React application. It also includes modifications to the `HomePage` component itself, improvements in error handling, and enhancements to the TypeScript parser functionality.
- The `HomePage` component now supports dynamic tab switching between global and personal feeds, along with tag filtering.
- The unit tests check for user-specific content rendering and handle cases where user data may be incomplete.
- Refactoring:
- The TypeScript parser was refactored to enhance its ability to parse classes, functions, and interfaces, including support for method visibility (public, private, protected) and async functions.
- The structure of the parsed data was improved to …
> fix: typescript parser

- examples/unittest/typescript_unittest.py
- kaizen/actors/unit_test_runner.py
- kaizen/generator/unit_test.py
- kaizen/helpers/general.py
- kaizen/parsers/typescriptparser.py
This pull request primarily focuses on improving the TypeScript unit test runner by enhancing path safety, refining regex patterns for better readability, and implementing a new utility function for path management. These changes aim to increase the robustness and maintainability of the codebase.
- Key Changes:
- Introduced a new `safe_path_join` function to ensure that file paths remain within a specified base directory, preventing potential security issues related to path traversal.
- Updated the `UnitTestRunner` class to utilize `safe_path_join` for constructing file paths, enhancing the safety and clarity of the code.
- None explicitly mentioned in the PR, but the addition of path safety can be considered a feature that enhances the overall functionality of the unit …
> fix: fixed file path joining issue

- example/unittest/tests/examples/unittest/python_sample/test_calculate_late_fee.py
- example/unittest/tests/examples/unittest/python_sample/test_format_book_info.py
- example/unittest/tests/examples/unittest/python_sample/test_library.py
- examples/unittest/main.py
- examples/unittest/python_sample/library.py
- kaizen/generator/unit_test.py
- pyproject.toml
This pull request introduces a suite of unit tests for the library management system, focusing on the functionality of calculating late fees, formatting book information, and managing library operations. The tests cover normal cases, edge cases, error handling, and boundary conditions, ensuring robust validation of the library's features.
- **New Features:**
- Introduced parameterized testing for late fee calculation, allowing for concise and clear test definitions.
- Added error handling tests for missing book information in the `format_book_info` function to ensure robustness against incomplete data.
- The main test generation script now includes a more flexible approach to running tests from a directory, enhancing usability and maintainability.
- Consolidated …
> feat: updated token usage for unit test generation

- kaizen/llms/prompts/code_scan_prompts.py
This pull request aims to improve the code scanning prompts used in the Kaizen project. The changes focus on enhancing the information provided in the output format to better assist developers in understanding and addressing the identified issues.
- Key Changes:
- Renamed the `code_sample` field to `solution` to better reflect the purpose of providing example code to fix the issue.
- Improved the field descriptions to provide more clarity on the expected content for each field.
- Refactoring:
- Standardized the field names and descriptions across the two code scanning prompt examples for consistency.
- The updated prompts now include a `solution` field that allows providing example code to address the identified issue, in addition to the existing `suggestion` field for a textual …
> feat: updated the pronmpt

- kaizen/llms/prompts/pr_desc_prompts.py
This pull request enhances the functionality of the `pr_desc_prompts.py` module to generate more comprehensive and informative pull request descriptions. The changes focus on improving the structure and content of the generated summaries to provide better context for reviewers.
- Key Changes:
- Added a new section to display the original pull request description in a collapsible details block
- Refined the summary structure to include a clear overview of the main purpose and changes
- Improved the formatting and readability of the generated markdown
- Ability to generate a concise summary of the pull request's main purpose
- Inclusion of key changes, new features, and refactoring details in a structured format
- Refactoring:
- Reorganized the prompt template to better …
> ENH: Add collapsed section in modified PR containing original description

- kaizen/llms/prompts/unit_tests_prompts.py
- pyproject.toml
This pull request aims to update the project version and enhance the test coverage by implementing additional assertions in the unit tests. The changes ensure that the codebase remains robust and that the tests accurately verify the expected behavior of the implemented features.
- Key Changes:
- Updated the project version from `0.3.23` to `0.3.24` in the `pyproject.toml` file.
- Added assertions in the unit tests to verify expected behavior, improving test reliability.
- None specified in this PR; however, the enhancements to the test assertions can be considered a feature in terms of improved test coverage.
- Refactoring:
- No significant refactoring changes were made; the focus was primarily on enhancing test assertions.
> ✨ Generated with love by …
> 430 feat dont generate test cases for test cases

- kaizen/llms/prompts/pr_desc_prompts.py
This pull request enhances the error handling and logging capabilities of the PR description generator. It introduces more robust error handling to provide better feedback to users and improve the overall reliability of the tool.
- Key Changes:
- Implemented try-except blocks to catch and handle various types of exceptions that may occur during the PR description generation process.
- Added detailed error messages that provide more context about the issue, including the specific error type and a brief explanation.
- Improved logging to capture relevant information, such as the input data and the encountered error, to aid in troubleshooting and debugging.
- Introduced a new logging module to centralize and standardize the logging functionality across the codebase.
- …
> feat: updated description generation prompt

- kaizen/llms/prompts/code_review_prompts.py
This pull request enhances the code review prompt generation by providing more context and guidance for reviewers. It aims to improve the quality and efficiency of code reviews by providing clear instructions and expectations.
- Added explanations for each line in the diff, highlighting changes and their context.
- Clarified the purpose of each field in the review prompt data structure.
- Provided an example of a diff with explanations for better understanding.
- **New Features:**
- None
- None
<details>
</details>
> feat: updated the code review with 1 shot prompting

- pyproject.toml
This pull request updates the version of the `kaizen-cloudcode` package from `0.4.0` to `0.4.1`. This is likely a minor version bump to introduce bug fixes, improvements, or small new features to the existing functionality.
- Key Changes: Bumped the version number from `0.4.0` to `0.4.1` in the `pyproject.toml` file.
- New Features: No new features are explicitly mentioned, so this is likely a minor release focused on improvements and bug fixes.
- Refactoring: No significant refactoring is indicated in the provided information.
<details>
</details>
> fix: bug fix for pr deescription generation

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
This pull request introduces a configuration for pre-commit hooks to enforce code quality standards using Flake8 and Black, along with updates to the project's dependency management by adding several new packages in the `poetry.lock` file. These changes aim to improve code readability, maintainability, and overall development workflow.
- Key Changes:
- Added a new `.pre-commit-config.yaml` file to integrate Flake8 and Black for code linting and formatting.
- Updated `pyproject.toml` to include the `pre-commit` package as a dependency.
- Integration of Flake8 for linting, which helps in identifying potential errors and enforcing coding style.
- Integration of Black for automatic code formatting, ensuring consistent code style across the project.
- Refactoring:
- The …
> feat: added pre commit

- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request focuses on refactoring and improving the code review functionality in the `kaizen-cloudcode` project. The changes aim to enhance the efficiency, readability, and maintainability of the code review process.
- Key Changes:
- Optimized the `_process_files` method to use a generator-based approach, reducing memory usage and improving performance.
- Moved the `available_tokens` check to the beginning of the `_process_files_generator` method, ensuring that the necessary tokens are available before processing files.
- Simplified the logic in the `_process_files` method by separating the file processing and code quality calculation.
- Refactoring:
- Refactored the `_process_files_generator` method to use a more efficient and readable generator-based approach.
- Improved the …
> feat: updated file generator script

- kaizen/helpers/parser.py
- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request aims to enhance the efficiency of the code review process by providing an option to ignore deletions when generating the code diff summary. This change can help reduce the amount of information presented to the reviewer, allowing them to focus more on the added and modified code, which is typically the primary focus of a code review.
- Key Changes: Added an `ignore_deletions` parameter to the `patch_to_combined_chunks` function in the `parser.py` module, which allows the code review process to skip the formatting and inclusion of deleted lines in the code diff summary.
- New Features: Introduced a new `ignore_deletions` attribute in the `CodeReviewManager` class, which can be set to `True` to enable the deletion-ignoring behavior.
- Refactoring: Updated the …
> 451 linting add pre commit

- examples/unittest/main.py
- kaizen/actors/unit_test_runner.py
- kaizen/generator/unit_test.py
- kaizen/llms/provider.py
This pull request introduces enhancements to the unit test runner functionality, allowing users to execute tests for specific files in addition to running all tests. This improves flexibility and usability for developers.
- Modified `discover_and_run_tests` method to accept an optional `test_file` parameter, enabling targeted test execution.
- Updated the `run_tests` method in the generator to pass the `test_file` parameter to the unit test runner.
- Added logging to indicate when no specific test file is provided, enhancing user feedback.
- Users can now run a single test file by specifying the `file_path` parameter in the `run_tests` method.
- Improved logging within the `discover_and_run_tests` method to clarify the execution flow and …
> feat: added support for running single file tests

- examples/code_review/main.py
- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request aims to enhance the code review functionality in the Kaizen project. The key changes include improvements to the file processing logic, error handling, and overall code quality.
- Key Changes:
- Refactored the `_process_files` and `_process_files_generator` methods to handle cases where there is no data to process, returning `None` instead of an empty list.
- Updated the `_process_file_chunk` method to return `None` if there is no diff data, instead of returning an empty list.
- Improved the logic for determining the overall code quality by comparing the quality of each file and keeping track of the lowest value.
- Added the `code_quality` parameter to the `create_pr_review_text` function, allowing the review text to be generated based on the overall code …
> 480 add functionality to test a single file if specified

- kaizen/actors/unit_test_runner.py
- kaizen/generator/unit_test.py
This pull request enhances the unit test runner and generator by improving logging practices and introducing a temporary directory parameter for test generation.
- Updated logging message formatting in the `discover_and_run_tests` method for consistency.
- Added a `temp_dir` parameter to the `generate_tests` function to allow for temporary directory specification during test generation.
- Introduced functionality to handle a temporary directory in the test generation process, enhancing flexibility in file management.
- Improved readability by replacing string formatting in the logging messages and ensuring consistent use of double quotes.
<details>
<details>
<summary>Original …
> feat: remove temp file path

- kaizen/reviewer/code_scan.py
This pull request enhances the code scanning and reporting functionality in the `CodeScanner` class. The changes aim to provide more comprehensive and informative code review outputs, including tracking the total number of files processed and the number of files successfully processed.
- Key Changes:
- Added two new attributes to the `CodeScanOutput` class: `total_files` and `files_processed` to track the total number of files scanned and the number of files successfully processed.
- Updated the `review_code_dir` method to increment the `files_processed` counter for each file that is successfully reviewed.
- Included the `total_files` and `files_processed` attributes in the final `CodeScanOutput` object returned by the `review_code_dir` method.
- None
- Refactoring:
- No …
> feat: added file count in scan output

- kaizen/generator/issue_analysis.py
- kaizen/retriever/llama_index_retriever.py
- pyproject.toml
This pull request aims to improve the issue analysis and code retrieval functionality of the Kaizen application. The changes focus on enhancing the accuracy and efficiency of issue label generation, issue description generation, and code retrieval from the repository.
- Improved error handling for missing issue labels and descriptions
- Optimized token usage tracking and cost calculation for LLM interactions
- Refactored code to improve readability and maintainability
- Added support for tracking the total number of files processed during repository setup
- Introduced tracking of embedding usage metrics separately from the overall LLM usage
- Reorganized and simplified the `_process_issue_for_labels` and `_process_issue_for_desc` methods
- Consolidated token usage tracking and cost …
> 491 feat add embedding usage count and file counts for retriever module

- .experiments/code_review/evaluate.py
- kaizen/helpers/parser.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/tests/helpers/test_patch_parser.py
This pull request introduces significant improvements to the patch parsing functionality in the codebase. The main goal is to enhance the accuracy and flexibility of the patch parsing process, enabling more robust code review capabilities.
- Key Changes:
- Refactored the `patch_to_separate_chunks` and `patch_to_combined_chunks` functions to handle various edge cases more effectively.
- Introduced an `ignore_deletions` parameter in the `patch_to_combined_chunks` function to allow for selective handling of deleted lines.
- Improved the `format_change` function to provide more informative and readable output, including line number formatting.
- Updated the `code_review_prompts` module to align with the new patch parsing functionality and provide clearer guidelines for code reviewers.
- New …
> feat: updated the code review prompt and added usage for retriever

- kaizen/llms/prompts/code_review_prompts.py
diff --git a/kaizen/llms/prompts/code_review_prompts.py b/kaizen/llms/prompts/code_review_prompts.py
index bfcdc84..875e5f1 100644
--- a/kaizen/llms/prompts/code_review_prompts.py
+++ b/kaizen/llms/prompts/code_review_prompts.py
@@ -19,7 +19,8 @@
"start_line": <STARTING_LINE_NUMBER>,
"end_line": <ENDING_LINE_NUMBER>,
"sentiment": "positive|negative|neutral",
-      "severity": <1_TO_10>
+      "severity": <1_TO_10>,
+      "type": "general|performance|security|refactoring|best_practices|duplication|maintainability|scalability|error_handling|resource_management|concurrency|dependencies|compatibility|accessibility|localization|efficiency|readability|naming"
}}
]
}}
@@ -38,7 +39,7 @@
- Provide specific feedback with file paths and line numbers
- Use markdown for code snippets. Make sure all …
> feat: updated the prompt with new fields.

- README.md
This pull request aims to enhance the clarity and conciseness of the README documentation related to the setup of the GitHub app for code review functionalities.
- Consolidated instructions regarding the necessity of the GitHub app for code review and clarified that other functionalities do not require it.
- Updated the link reference for the self-hosting guide to improve user navigation.
- None identified in this patch.
- Improved wording for better readability and comprehension in the GitHub App Setup section.
<details>
<details>
</details>
> [DOC] Updated README.md's redirection link to Kaizen documentation

- kaizen/helpers/parser.py
- kaizen/tests/helpers/test_diff_to_numbered_lines.py
This pull request enhances the patch processing functionality by refactoring existing methods and introducing new features for generating pull request descriptions. The changes aim to improve code readability, maintainability, and the overall user experience when summarizing pull requests.
- Renamed `patch_to_separate_chunks` to `patch_to_numbered_lines` for clarity.
- Removed unnecessary variables related to removals, simplifying the logic.
- Improved handling of addition lines with better formatting.
- Introduced a new helper function `format_add_linenum` to standardize line number formatting.
- Added a new prompt for generating structured pull request descriptions, enhancing the clarity and organization of output.
- Implemented a new file …
> feat: added function to give diff with line numbers

- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request aims to enhance the code review functionality of the Kaizen project. It introduces several key improvements, including the ability to provide custom context during the review process, handle file-level code reviews more efficiently, and re-evaluate the generated review responses.
- Key Changes:
- Added support for providing custom context during the code review process, which can be used to provide additional information or instructions to the language model.
- Optimized the file-level code review process by introducing a generator-based approach to handle large diffs more efficiently.
- Implemented a re-evaluation mechanism for the generated review responses, allowing the reviewer to refine the feedback based on specific user requirements.
- Custom …
> feat: added custom context for code review

- .github/workflows/kaizen-tests.yml
- cli/kaizen_cli/cli.py
- cli/pyproject.toml
This pull request introduces a new unit test generation and execution functionality to the Kaizen CLI. The main purpose is to enable developers to easily generate and run unit tests for their code, with options to enable code critique, customize output, and control the verbosity and maximum number of critiques.
- Added a new `unit_test` command group to the CLI, with subcommands for generating tests, generating tests for a directory, and running tests.
- Implemented the `UnitTestGenerator` class to handle the generation and execution of unit tests.
- Added options to the unit test commands to control the output folder, enable code critique, set verbosity, and limit the maximum number of critiques.
- Ability to generate unit tests for a single file or an entire directory.
- Option to …
> feat: added unit test runner

- cli/poetry.lock
- cli/pyproject.toml
This pull request primarily focuses on updating the dependency management and versioning for the Kaizen CLI project. It introduces changes to the `pyproject.toml` and `poetry.lock` files to streamline dependency specifications and improve compatibility with Python versions.
- Key Changes:
- Updated the Python version specification to use caret (`^`) notation for better compatibility.
- Adjusted the versioning of the `kaizen-cloudcode` dependency to facilitate development and production environments.
- Modified the `poetry.lock` file to reflect the updated dependency versions and constraints.
- Introduced a new development group for `kaizen-cloudcode`, allowing for easier management of development dependencies.
- Refactoring:
- Removed specific version constraints for …
> 505 feat add unit test actions

- cli/kaizen_cli/cli.py
- cli/pyproject.toml
This pull request enhances the unit test running capabilities of the Kaizen CLI by introducing a dedicated `UnitTestRunner` class and integrating it into the existing `run_tests` command. The changes aim to improve the overall user experience and testability of the application.
- Key Changes:
- Replaced the `UnitTestGenerator` class with a new `UnitTestRunner` class to handle the discovery and execution of unit tests.
- Updated the `run_tests` command in the CLI to use the `UnitTestRunner` instead of the previous `UnitTestGenerator`.
- Improved the output formatting of the test results, providing more detailed information on errors and failures.
- Added the ability to run unit tests for a specific file path, allowing users to target individual test suites.
- Refactoring:
- …
> feat: updated the cli unittest execution

- kaizen/generator/pr_description.py
- kaizen/llms/prompts/pr_desc_prompts.py
This pull request enhances the functionality of the PR description generator to provide more concise and actionable summaries. The key changes focus on streamlining the output format, prioritizing the most significant modifications, and eliminating redundant or minor details.
- Key Changes:
- Simplified the output format to focus on the core purpose, key changes, and potential impact.
- Reduced the number of sections to keep the summary more compact and readable.
- Prioritized the most critical modifications and features, avoiding repetition of minor details.
- Improved the instructions to guide the generator towards generating focused, high-impact summaries.
- Refactoring:
- Consolidated the `PR_FILE_DESCRIPTION_PROMPT` and `PR_DESCRIPTION_PROMPT` into a single, more versatile prompt.
- …
> feat: pushed pr description

- kaizen/reviewer/code_review.py
- pyproject.toml
This pull request aims to improve the code review functionality in the `kaizen-cloudcode` project. It introduces a new feature to optionally check for sensitive files during the review process and provides a way to customize the review context.
- Key Changes:
- Added a new parameter `check_sensetive` to the `review_pull_request` function, which allows the caller to enable or disable the check for sensitive files.
- Refactored the `review_pull_request` function to only execute the `check_sensitive_files` method if the `check_sensetive` parameter is set to `True`.
- Updated the `pyproject.toml` file to increment the version number from `0.4.8` to `0.4.9`.
- Introduced the ability to provide a custom context string to the review process through the `custom_context` parameter …
> feat: made sensetive file optional

- kaizen/llms/provider.py
- **Purpose:**
Enhance the LLM provider module with better type annotations and more robust usage tracking.
- Added type annotations to several functions for improved code clarity and maintainability.
- Expanded the return types of `chat_completion` and `raw_chat_completion` to include a tuple with the response and usage statistics.
- Improved the `get_usage_cost` method to return a tuple with the total cost and the cost breakdown per token type.
- **Impact:**
These changes will provide better type safety, more detailed usage reporting, and a more robust LLM integration for the Kaizen platform.
<details>
</details>
> fix: output type of functions

- docs/pages/_meta.json
- **Purpose:**
Update the sidebar navigation links in the documentation.
- Renamed "API Reference" to "SDK Reference"
- Adjusted the order and titles of some navigation links
- **Impact:**
This change will improve the organization and clarity of the documentation sidebar, making it easier for users to navigate and find relevant information.
<details>
</details>
> [docs]: renaming api to sdk at meta.json

- kaizen/retriever/code_chunker.py
- kaizen/retriever/llama_index_retriever.py
- kaizen/retriever/qdrant_vector_store.py
- kaizen/retriever/tree_sitter_utils.py
- **Purpose:**
Enhance the code chunking and retrieval functionality by adding line number information and improving the database storage and querying.
- Added start and end line numbers to the parsed code information in `code_chunker.py`.
- Improved the `store_code_in_db()` function in `llama_index_retriever.py` to store the start and end lines for each code snippet.
- Refactored the `store_function_relationships()` method to use a more flexible query format.
- Updated the `qdrant_vector_store.py` to connect to Qdrant with an API key.
- Added line number information to the `traverse_tree()` function in `tree_sitter_utils.py`.
- **Impact:**
These changes will provide more detailed information about the code snippets, enabling better code understanding and retrieval. The …
> feat: updated the retriever for custom API Key and SQL storage

- README.md
- pyproject.toml
- **Purpose:**
Update the README with new features and bump the package version.
- Added a new section for "Key Features" highlighting the AI-powered code reviews and smart test generation capabilities.
- Bumped the package version from 0.4.11 to 0.4.12 in the `pyproject.toml` file.
- **Impact:**
These changes will provide users with a more comprehensive understanding of the tool's capabilities and ensure they have access to the latest version with potential bug fixes or improvements.
<details>
</details>
> updated new release version

- cli/kaizen_cli/cli.py
- cli/kaizen_cli/config/default_config.py
- cli/kaizen_cli/hooks/prepare-commit-msg
- cli/kaizen_cli/hooks/setup.py
- cli/poetry.lock
- cli/pyproject.toml
- kaizen/retriever/code_chunker.py
- kaizen/retriever/llama_index_retriever.py
- kaizen/retriever/qdrant_vector_store.py
- kaizen/retriever/tree_sitter_utils.py
- kaizen/utils/config.py
- pyproject.toml
- **Purpose:**
Enhance the code chunking and abstraction generation capabilities of the Kaizen CLI tool.
- Expanded the `chunk_code` function to extract more code elements, including imports, global variables, type definitions, async functions, and JSX elements.
- Improved the `generate_abstraction` function to generate more detailed and structured JSON-formatted abstractions, including sections for summary, functionality, inputs, output, dependencies, algorithms, edge cases, error handling, usage context, complexity, tags, testing considerations, and more.
- Added support for storing code metadata (file path, function name, start/end lines) in the database along with the generated abstractions.
- **Impact:**
These changes will improve the quality and comprehensiveness …
> 549 kaizen cli make easy setup with ollama

- kaizen/retriever/code_chunker.py
- kaizen/retriever/llama_index_retriever.py
- **Purpose:**
Enhance the code chunking process and optimize file path handling in the retriever module.
- Added a new function `clean_filename` to remove the `tmp` directory from file paths.
- Removed the `analyze_function_calls` method, as it is no longer needed.
- Updated the `store_code_in_db` method to use the cleaned file path for storing code in the database.
- **Impact:**
These changes will improve the reliability and maintainability of the code chunking and file path handling processes, leading to better performance and data integrity.
<details>
</details>
> added feature to clean the path name

- cli/poetry.lock
- cli/pyproject.toml
- **Purpose:**
Update the kaizen-cloudcode dependency to the latest version (0.4.15).
- Updated the kaizen-cloudcode dependency version in the poetry.lock and pyproject.toml files.
- No other functional changes were made in this pull request.
- **Impact:**
This update will bring in the latest features, bug fixes, and improvements from the kaizen-cloudcode library, enhancing the overall functionality and stability of the application.
<details>
</details>
> feat: updated kaizen version in cli app

- extensions/vscode/.vscodeignore
- extensions/vscode/README.md
- extensions/vscode/package.json
- **Purpose:**
Update the VSCode extension for the Kaizen-CloudCode platform, which provides AI-powered tools to automate development tasks.
- Removed the `out/` directory from the `.vscodeignore` file, allowing the compiled output to be included in the extension.
- Updated the `package.json` file with the extension's publisher, repository information, and a new activity bar icon and title.
- Revised the README file to provide a brief description of the extension's main feature: API management.
- **Impact:**
These changes improve the packaging and presentation of the Kaizen-CloudCode VSCode extension, making it more accessible and informative for users.
<details> …
> docs: update README and configuration for clarity

- .experiments/code_review/dataset/pr_5/issues.json
- .experiments/code_review/main.py
- kaizen/generator/pr_description.py
- kaizen/helpers/parser.py
- kaizen/llms/prompts/code_review_prompts.py
- kaizen/llms/provider.py
- kaizen/reviewer/code_review.py
- pyproject.toml
- **Purpose:**
Improve the code review process by optimizing diff handling and error management.
- Added retry logic for API calls with exponential backoff to enhance reliability.
- Introduced combined diff data handling for better context in reviews.
- Removed redundant code checks and improved progress printing efficiency.
- Updated version number to 0.4.16 in `pyproject.toml`.
- Enhanced file exclusion logic to streamline processing.
- **Impact:**
These changes will lead to a more efficient and reliable code review process, reducing errors and improving performance.
<details>
- ****Purpose:**
**
Improve the efficiency and clarity of the pull request review process.
- …
> feat: enhance pr review process and code quality

- examples/unittest/runner.py
- kaizen/actors/unit_test_runner.py
- **Purpose:**
Improve the UnitTestRunner to support parallel test execution and dynamic test discovery.
- Removed hardcoded test file paths, allowing discovery of all test files in the specified directory.
- Implemented parallel test execution using `ThreadPoolExecutor`.
- Enhanced project root detection with caching for efficiency.
- Simplified command execution error handling.
- Streamlined logging and output parsing for various test frameworks.
- **Impact:**
This refactor increases test execution efficiency and flexibility, making it easier to manage and run tests across multiple languages.
<details>
Improve the UnitTestRunner by enabling parallel test execution and …
> refactor: enhance UnitTestRunner for test execution

- extensions/vscode/src/apiRequest/apiRequestView.ts
- **Purpose:**
Improve the display of JSON responses in the API request view.
- Added CSS styles for better JSON formatting.
- Introduced a `formatJSON` function to format JSON strings with syntax highlighting.
- Updated the response handling to format the body and headers as JSON when applicable.
- **Impact:**
Enhances readability of JSON responses, making it easier for users to analyze API data.
<details>
None
</details>
> UI changes to API request

- extensions/vscode/README.md
- extensions/vscode/package.json
- extensions/vscode/src/SidebarProvider.ts
- **Purpose:**
Improve the Kaizen VS Code extension with new features and functionality.
- Added sidebar buttons for "API Documentation", "Documentation", "Test Management", and "Code Review" (currently marked as "Coming Soon").
- Implemented a circular buffer to manage the API history, limiting it to the last 10 entries.
- Added logic to save and load the API history using the extension's global state.
- Improved the update process for API history, ensuring that existing entries are updated instead of creating duplicates.
- Implemented a method to delete API endpoints from the history.
- **Impact:**
These changes enhance the user experience of the Kaizen extension by providing a more organized and persistent API management system. The addition of new sidebar features …
> updated vscode version

- README.md
- kaizen/llms/prompts/code_scan_prompts.py
- **Purpose:**
Update the README file to move the logo image to the correct location and update the contribution guidelines link.
- Moved the logo image from `/assets/logo.png` to `/docs/public/logo.png`.
- Updated the link to the contribution guidelines from a relative path to an absolute GitHub link.
- **Impact:**
These changes will ensure the logo is displayed correctly and provide users with the correct information for contributing to the project.
<details>
- ****Purpose:**
**
Improve documentation and enhance security checks in code scanning prompts.
- ****Key Changes:****
- Updated logo path in README from assets to docs directory.
- Changed the link for …
> 621 readme cleanup

- poetry.lock
- pyproject.toml
- **Purpose:**
Upgrade FastAPI and Starlette to their latest versions for improved performance and features.
- Updated FastAPI from version 0.110.3 to 0.115.2.
- Updated Starlette from version 0.37.2 to 0.40.0.
- Modified dependency constraints for Starlette in the poetry.lock file.
- Added `fastapi-cli` to the extras section in the poetry.lock file.
- Adjusted content hash in the poetry.lock file for consistency.
- **Impact:**
These updates may enhance application performance and compatibility with newer features in FastAPI and Starlette.
<details>
- ****Purpose:**
**
Upgrade FastAPI and Starlette to their latest versions for improved performance and features.
- ****Key …
> fix: security updates
