README.md, docs/pages/github_app.md
This pull request aims to enhance the documentation by adding detailed information about setting up the GitHub app for the CloudCode repository.
- Added a new file `github_app.md` under the `docs/pages` directory, providing a comprehensive guide on setting up the GitHub app.
- Updated the `README.md` to include a new section 'Running API Server for GitHub App' with instructions on deploying the API using Docker Compose and configuring features.
The motivation behind these changes is to improve the onboarding experience for new users and contributors by providing clear and detailed instructions on setting up the GitHub app for the CloudCode repository. Additionally, the update to the `README.md` aims to streamline the process of running the API server for the GitHub app.
-- Generated with …
=> 19 doc add GitHub app setup page

kaizen/helpers/output.py
This pull request aims to fix the comment decomposition issue in the `output.py` file within the `kaizen/helpers` directory.
- The code modification involves replacing the `comment.decompose()` method with `comment.extract()` to address the comment decomposition issue.
The motivation behind these changes is to resolve the issue where the `comment.decompose()` method was not functioning as expected, leading to incomplete comment removal. By using `comment.extract()`, the code aims to ensure proper and complete removal of comments, enhancing the overall functionality and maintainability of the codebase.
-- Generated with love by Kaizen
<details>
None
</details>
=> fix: comment decomposition issue fixed

examples/basic/execute.py, examples/work_summarizer/main.py, kaizen/helpers/output.py, kaizen/helpers/parser.py, kaizen/llms/prompts.py, kaizen/llms/provider.py, kaizen/reviewer/code_review.py, kaizen/reviewer/work_summarizer.py
This pull request introduces the work summary reporting functionality, including the addition of a new module 'work_summarizer' and related changes in existing files.
1. Added 'work_summarizer' module with 'WorkSummaryGenerator' class for generating work summaries based on provided diff data.
2. Modified 'execute.py' to include functionality for retrieving GitHub commits and generating work summaries.
3. Updated 'output.py', 'parser.py', 'prompts.py', 'provider.py', and 'code_review.py' to support the work summary reporting functionality.
The changes aim to enhance the code review process by automatically generating user-friendly work summaries for non-technical stakeholders. This functionality leverages the GitHub API to retrieve commit data and provides a high-level overview of code …
=> 92 add work summary reporting functionality

.github/workflows/ pypi-publish.yml
This pull request aims to fix the Python CI/CD run by adjusting the Python version and installing Poetry. The changes are made in the '.github/workflows/pypi-publish.yml' file. The Python version is downgraded from 3.10 to 3.9, and Poetry is installed using 'pip install poetry'. The motivation behind these changes is to ensure compatibility and stability in the CI/CD pipeline, as well as to align with the project's dependencies and requirements.
-- Generated with love by Kaizen
<details>
None
</details>
=> fix: python CI CD run

kaizen/helpers/output.py, kaizen/utils/config.py, poetry.lock, pyproject.toml, tests/actions/test_review.py
This pull request introduces changes aimed at adding an alternative setup to the `config.json` file and updating dependencies.
1. In `output.py`, the import statement was modified to use `kaizen.helpers` instead of `general`.
2. In `config.py`, the `get_config` function was updated to dynamically locate the `config.json` file and provide default values if the file is not found.
3. Dependencies in `poetry.lock` and `pyproject.toml` were updated, including the addition of the `fuzzywuzzy` package.
The changes aim to improve the flexibility and robustness of the configuration setup by allowing an alternative location for the `config.json` file. Additionally, updating dependencies ensures compatibility and potentially introduces new functionality through the `fuzzywuzzy` package.
-- Generated …
=> 104 add alternative setup to configjson

kaizen/llms/prompts.py
This pull request aims to update the `prompts.py` file in the `kaizen/llms` directory. The main purpose is to correct a spelling mistake by replacing 'seperate' with 'separate' in the UI_MODULES_PROMPT string. This change is a simple modification to improve the accuracy and clarity of the prompt.
The significant modification in this pull request is the correction of the spelling error in the UI_MODULES_PROMPT string. No new features or refactoring are introduced, as the change is limited to a single string.
The motivation behind this change is to maintain consistency and accuracy in the codebase. By correcting the spelling mistake, the prompt will be more clear and accurate, aligning with best practices for code quality and readability.
<details> …
=> docs: update prompts.py

kaizen/reviewer/code_review.py
This pull request aims to address the issue of missing model name in the return response. The changes involve adding the 'model_name' attribute to the return response in the 'review_pull_request' and 'generate_pull_request_desc' functions within the 'code_review.py' file.
- Added 'model_name' attribute to the return response in 'review_pull_request' and 'generate_pull_request_desc' functions.
The motivation behind these changes is to ensure that the model name is included in the return response, providing more comprehensive and informative data for the users and improving the overall functionality and usability of the code.
<details>
None
</details>
=> fix: added model name to the return response

README.md, pyproject.toml
This pull request aims to update the installation guide for Kaizen. It introduces changes to the README.md file and the pyproject.toml file.
- Updated the installation steps in README.md to reflect the correct package installation process.
- Modified the version number in pyproject.toml from 0.1.8 to 0.1.9.
The motivation behind these changes is to ensure that users can easily install Kaizen by providing accurate installation instructions. Additionally, updating the version number in pyproject.toml reflects the latest release of the Kaizen package.
<details>
None
</details>
=> fix: updated installation guide

kaizen/reviewer/code_review.py
This pull request aims to address a bug related to the 'keyname not found in patch' issue in the code_review.py file within the kaizen/reviewer module.
- Refactored the code to handle potential None values for 'patch' and 'filename' attributes to prevent potential KeyError.
- Added a conditional check for 'patch_details' to ensure it's not None before processing.
The changes focus on improving error handling and preventing potential issues related to missing 'patch' or 'filename' attributes, ultimately enhancing the reliability and robustness of the code.
<details>
None
</details>
=> bugfix: keyname not found in patch

kaizen/helpers/output.py, kaizen/llms/prompts.py
This pull request introduces changes to the prompt output format and refactors the code to include new features for generating feedback.
- Updated the prompt output format in output.py to include start and end line numbers and file name.
- Refactored the code in prompts.py to include start and end line numbers and file name for each comment.
- Added instructions for generating all possible feedbacks and providing actionable points for each comment.
- Improved the clarity and specificity of feedback by referencing specific file(s) and line number(s) of code being addressed for each comment.
- Utilized markdown code blocks to quote relevant snippets of code when necessary for better readability.
<details>
None …
=> feat: updated the prompt output format

kaizen/helpers/output.py, kaizen/reviewer/code_review.py, pyproject.toml, tests/actions/test_review.py, tests/helpers/test_output.py
This pull request aims to update the code review output format for granular control. The significant modifications include:
- Refactoring the `create_pr_review_from_json` function into the `CodeReviewer` class
- Introducing the `merge_topics` and `create_pr_review_text` methods to handle topic merging and review text creation
- Adding the `is_code_review_prompt_within_limit` method to check the token limit for code review prompts
- Updating the version to 0.1.11 in the `pyproject.toml` file
- Adding tests for the new methods and functionality
These changes enhance the code review process by providing more control over the output format and improving the efficiency of code review prompts. The refactoring and new features contribute to better maintainability and readability of the codebase. …
=> fix: updating code review output format for granular control

kaizen/llms/prompts.py
This pull request aims to update the prompt in the code to make the feedback more concise and actionable.
- Modified the code review prompt to emphasize providing concise and actionable feedback.
- Removed redundant instructions and clarified the goal of the code review prompt.
- Updated the file code review prompt to align with the changes made in the code review prompt.
The changes aim to improve the clarity and effectiveness of the code review process by providing specific guidance on delivering actionable feedback.
<details>
None
</details>
=> fix: updated prompt to make feedback more concise

config.json, kaizen/llms/provider.py
This pull request aims to add model update functionality and make related code modifications.
- Added a new model 'gpt-3.5-turbo-1106' to the 'language_model' section in 'config.json'.
- Refactored the 'provider.py' file to update the model based on the configuration data.
- Introduced a conditional check to update the model based on the configuration.
<details>
None
</details>
=> fix: added model update functionality

config.json, kaizen/llms/provider.py
This pull request aims to address the issue of custom token pricing by introducing changes to the configuration and provider files.
- In the `config.json` file, the language model's `model` attribute has been replaced with a nested object containing `name`, `input_token_cost`, and `output_token_cost` properties.
- In the `provider.py` file, default input and output token costs have been added to the `LLMProvider` class, and the `chat_completion` method has been updated to utilize the new token cost values.
These modifications enable the customization of token pricing for the language model, providing more flexibility and control over the cost associated with input and output tokens.
<details>
None
</details>
=> fix: added custom token pricing

kaizen/reviewer/code_review.py, pyproject.toml
This pull request aims to fix the review generation process by updating it with the new topics system. Additionally, it includes a version update in the pyproject.toml file from 0.1.11 to 0.1.12.
- In the code_review.py file, the modification involves updating the extraction of reviews from a JSON response.
- The pyproject.toml file has been updated to change the version from 0.1.11 to 0.1.12.
<details>
None
</details>
=> fix: updated the review generation with new topics system

kaizen/helpers/output.py, kaizen/llms/prompts.py, kaizen/reviewer/code_review.py, pyproject.toml
This pull request introduces changes to update the prompt to provide a solution. The scope of the changes includes modifying the prompt structure and updating the PR_COLLAPSIBLE_TEMPLATE in output.py. Additionally, it updates the version in pyproject.toml to 0.1.13.
- In kaizen/helpers/output.py, the PR_COLLAPSIBLE_TEMPLATE has been updated to include a new 'solution' field in the summary.
- In kaizen/llms/prompts.py, the 'confidence' and 'solution' fields have been updated in the prompt structure.
- In kaizen/reviewer/code_review.py, the 'solution' field has been added to the PR_COLLAPSIBLE_TEMPLATE.
- The version in pyproject.toml has been updated to 0.1.13.
<details>
None
</details>
=> feat: updated the prompt to provide solution

kaizen/llms/prompts.py
This pull request aims to update the prompt in the `prompts.py` file to add a confidence level based on the severity of the issue. The main scope of the changes is to enhance the prompt by providing more context related to the severity of the issue.
- Updated the prompt to include confidence levels based on the severity of the issue, providing more detailed information to the users.
- Refactored the prompt content to ensure clarity and consistency in conveying the severity levels.
- No new features introduced, but the existing feature is improved by providing additional information to the users.
<details>
None
</details>
=> fix: updated prompt to add confidence level based on severity of issue

kaizen/llms/provider.py, kaizen/reviewer/code_review.py
This pull request introduces changes to the codebase with the main purpose of updating the chat_completion method in provider.py and modifying the create_pr_review_text method in code_review.py. Notable modifications include adding input and output token cost handling, refactoring the markdown_output generation, and introducing a check for high-ranked issues in the code review text. The create_pr_review_text method now includes emojis to indicate the review status. The changes aim to improve the functionality and readability of the code while enhancing the code review process.
<details>
None
</details>
=> 147 if item in section are removed remove the title of topic

kaizen/helpers/output.py, kaizen/llms/provider.py, kaizen/reviewer/code_review.py
This pull request aims to update the messaging format used by the Kaizen bot to improve clarity and user experience. The changes primarily focus on modifying the output templates and the review status messages.
1. **Output Template Update**:
- The `PR_COLLAPSIBLE_TEMPLATE` in `kaizen/helpers/output.py` has been updated to enhance readability.
- The summary line now includes a newline character (`\n`) and the label `**Potential Solution:**` for better clarity.
- Additional newlines have been added for improved formatting.
2. **Review Status Messaging**:
- In `kaizen/reviewer/code_review.py`, the logic for generating the review status message has been refactored.
- The status message is now stored in a variable `status_msg` and concatenated with the `markdown_title` and `markdown_output` …
=> fix: updated messaging for kaizen bot

kaizen/llms/provider.py, pyproject.toml
This pull request addresses a bug fix in the token counter functionality within the `kaizen/llms/provider.py` file. The main purpose of these changes is to correct the way tokens are counted by the `litellm.token_counter` function, ensuring that the correct parameters are passed to it.
1. **Bug Fix in Token Counter**: The `available_tokens` method in `kaizen/llms/provider.py` has been updated to pass the parameters to `litellm.token_counter` using keyword arguments (`model=self.model, text=message`) instead of positional arguments. This change ensures that the function receives the correct inputs, potentially fixing any issues related to incorrect token counting.
2. **Version Bump**: The project version in `pyproject.toml` has been incremented from `0.1.13` to `0.1.14`. This version bump …
=> 153 work summarizer token counter fix

kaizen/llms/provider.py, tests/llms/test_provider.py
This pull request addresses and resolves several flake8 issues in the `kaizen/llms/provider.py` and `tests/llms/test_provider.py` files. The main purpose of these changes is to improve code quality and maintainability by adhering to PEP 8 standards.
1. **Code Formatting:**
- In `kaizen/llms/provider.py`, the multi-line function call to `litellm.completion` has been refactored into a single line to comply with flake8 formatting rules.
- In `tests/llms/test_provider.py`, the assertion `assert response != None` has been corrected to `assert response is not None` to follow PEP 8 guidelines.
2. **Additional Assertions:**
- An additional assertion `assert usage is not None` has been added in `tests/llms/test_provider.py` to ensure that the `usage` variable is also checked for `None` values. …
=> fix: flake8 issues fixed

kaizen/llms/provider.py, kaizen/reviewer/code_review.py, kaizen/reviewer/work_summarizer.py
This pull request addresses an issue where the work summary wouldn't process the file if the available token count exceeded 0. It introduces several significant modifications and new features:
1. Addition of docstrings for methods `available_tokens`, `update_usage`, and `get_usage_cost` in `provider.py` for better code documentation.
2. In `code_review.py`, refactoring the status_msg assignment for better readability.
3. In `work_summarizer.py`, the addition of comments to explain the purpose of code blocks, improved handling of available tokens and the processing of remaining file diffs. Additionally, the introduction of the `total_usage` variable for tracking usage information and appending the generated response to the summaries list.
Overall, the changes aim to improve the handling of …
=> bugfix: work summary wouldnt process the file if available token > 0

README.md, kaizen/llms/prompts.py, pyproject.toml
This pull request aims to reduce the description size by removing unnecessary details and improving clarity. The main changes include adding a Discord badge to the README.md file, updating the version number in pyproject.toml to 0.1.17, and modifying PR_DESCRIPTION_PROMPT in prompts.py to enhance its clarity and accuracy. The code diff also reflects these changes. The pull request description is not provided, but the changes are clear from the code diff.
<details>
None
</details>
=> 163 reduce the description size

README.md
This pull request updates the README.md file with a demo link and a waitlist link, and also makes various improvements to the content of the file.
- Added demo and waitlist links
- Modified descriptions of Kaizen features
- Improved file structure section
- Updated the 'Getting Started' guide with clearer instructions
- Revised the 'Running API Server for GitHub App' section with an added note and code snippet
<details>
None
</details>
=> fix: Updated the readme file with demo and waitlist link

kaizen/generator/ui.py, kaizen/llms/prompts.py, kaizen/llms/provider.py
Adds formatting to the description generation process for the pull request.
- Refactored the code to format the description generation for the pull request.
- Enhanced readability and maintainability by reformatting the UI module identification and Playwright code generation sections.
- Applied consistent formatting to the `provider.py` file for improved code structure and consistency.
<details>
None
</details>
=> 170 add format to description generation for pr

github_app/github_helper/pull_requests.py, github_app/main.py
Updated the GitHub app to use updated Kaizen code, including refactoring and new features related to handling pull request reviews.
- Added confidence mapping for review confidence levels
- Updated process_pull_request function to handle review data and create review comments
- Refactored create_review_comments and clean_keys functions for better organization and readability
- Added new post_pull_request_comments function for posting review comments
- Updated handle_webhook function to handle new configuration data from ConfigData
- Removed unused code related to generating and running UI tests
<details>
None
</details>
=> feat: updated the github app to use updated kaizen code.

github_app/github_helper/pull_requests.py, kaizen/helpers/output.py, kaizen/llms/prompts.py, kaizen/reviewer/code_review.py
Added chunking for PR description generation
- Added `pr_files_url` variable to retrieve the URL of the PR files
- Modified the `process_pr_desc` function to fetch PR files using the `pr_files_url` variable
- Introduced a new function `create_pr_description` in the `output` module for generating PR descriptions
- Updated the `generate_pull_request_desc` function in the `code_review` module to handle chunking of large diffs
- Added a new prompt `MERGE_PR_DESCRIPTION_PROMPT` for merging multiple PR descriptions into a single description
- Modified the `generate_pull_request_desc` function to handle chunking based on files when the diff is too large
- Implemented chunking based on files by looping through the PR files and generating descriptions for each file
- Created a merged PR …
=> feat: added chunking for pr desc generation

.dockerignore, Dockerfile, docker-compose-dev.yml, github_app/github_helper/utils.py, kaizen/llms/prompts.py, kaizen/reviewer/code_review.py
Create a public docker image to deploy the GitHub app.
- Added `.dockerignore` file.
- Updated `Dockerfile` to use Python 3.12-slim image.
- Added `docker-compose-dev.yml` file to define development environment.
- Updated `docker-compose.yml` file to use the `cloudcodeai/kaizen-app` image.
- Updated `github_app/github_helper/utils.py` to read the PEM file path from an environment variable.
- Added missing import statements in `kaizen/llms/prompts.py`.
- Updated `kaizen/reviewer/code_review.py` to properly append descriptions to the `descs` list.
- Fixed formatting issues in `kaizen/reviewer/code_review.py`.
<details>
None
</details>
=> 194 craete a public docker image to deploy the GitHub app

kaizen/llms/prompts/code_review_prompts.py
Added instruction for 'request_for_change' in code_review_prompts.py
- Added specific guidance for setting 'request_for_change' to true in 'code_review_prompts.py'
- Emphasized setting 'request_for_change' only for topics related to 'Improvements' or 'Potential Issues'
- Clarified the conditions under which 'request_for_change' should be enabled
<details>
None
</details>
=> fix: added instruction for request_for_change

kaizen/generator/ui.py, kaizen/reviewer/code_review.py, kaizen/reviewer/work_summarizer.py, pyproject.toml
Updated handling of total_token logic for consistency across multiple modules.
- Introduced a structured approach to total_token handling by initializing `total_usage` with specific token categories.
- Updated `total_usage` initialization to include `prompt_tokens` and `completion_tokens` categories.
- Implemented the new token structure in multiple modules to ensure consistency.
- Refactored code in `ui.py`, `code_review.py`, and `work_summarizer.py` to incorporate the new token handling logic.
- Updated project version to `0.2.6` in `pyproject.toml` for version consistency.
<details>
None
</details>
=> updated how the total_token is handled

.github/workflows/ pypi-publish-cli.yml
Update CLI publishing workflow to use a new PyPI API token for authentication.
- Updated the PyPI publishing workflow in the '.github/workflows/pypi-publish-cli.yml' file to use a new PyPI API token for CLI publishing.
- Changed the value of the '--password' argument in the 'poetry publish' command to reference the updated API token variable.
<details>
None
</details>
=> update cli publishing

README.md
Add 'Install Kaizen App' button to the README page of the Kaizen project.
- Added 'Install Kaizen App' button to the README page
- Introduced a new feature to enable users to easily install the Kaizen app
<details>
None
</details>
=> 128 add button to kaizen app on readme page

kaizen/reviewer/code_review.py, pyproject.toml
Fixed a bug related to parsing large files during code review.
- Updated the version in pyproject.toml from 0.2.7 to 0.2.8
- Modified logic in code_review.py to handle large files, addressing a bug that caused incorrect behavior when assessing token limits
<details>
None
</details>
=> bug fix for large file review parsing

kaizen/generator/ui.py, kaizen/helpers/parser.py, kaizen/llms/prompts/work_summary_prompts.py, kaizen/reviewer/code_review.py, kaizen/reviewer/work_summarizer.py
Added error handling and retry mechanism using llm for JSON parsing to handle potential failures.
- Added new function 'extract_json_with_llm_retry' to handle JSON parsing with retry logic
- Modified 'review_pull_request' and 'generate_pull_request_desc' functions to use 'extract_json_with_llm_retry' for error handling
- Improved error resilience and user interaction by utilizing chat completion in case of JSON parsing failure
- Introduced 'total_usage' parameter for tracking usage throughout the process
- Refactored code for better error management and readability
- Updated pull request description generation to accommodate changes in error handling
<details>
None
</details>
=> fix: added llm based json parsing handling

cli/kaizen_cli/cli.py, cli/pyproject.toml
Added try-except blocks for error handling in kaizen CLI.
- Added try-except blocks in `load_config()` function to handle `JSONDecodeError` and `IOError` when reading the config file.
- Added try-except block in `save_config()` function to handle `IOError` when saving the config file.
- Updated version to 0.1.2 in pyproject.toml file
<details>
None
</details>
=> feat: Added try error block for kaizen cli

kaizen/reviewer/code_review.py, pyproject.toml
Updated code review methods to optionally re-evaluate prompts for more efficient processing and reduced resource usage.
- Added an optional `reeval_response` parameter to the `review_pull_request` and `generate_pull_request_desc` methods to enable/disable re-evaluation of prompts.
- None
- Enhanced the `review_pull_request` and `generate_pull_request_desc` methods to include a more flexible approach to handling evaluation prompts through the new `reeval_response` parameter.
- The `reeval_response` parameter is used to control whether the response from the AI model should be re-evaluated using another prompt.
- The modification of the existing methods improves the performance of the code by allowing users to opt-out of the re-evaluation process if it's not needed, saving computational …
=> made reeval of prompts optional

examples/work_summarizer/main.py, kaizen/reviewer/work_summarizer.py
Implemented work summary usage in response for social media posts
- Added the `total_usage` parameter in the `generate_twitter_post` and `generate_linkedin_post` methods of the `WorkSummarizer` class.
- Modified the main.py file to capture the `total_usage` returned from the newly updated methods.
- The social media post generation methods now return both the generated post content (markdown) and the `total_usage`.
<details>
None
</details>
=> fix: Added work summary usage in response for social media posts

.github/workflows/update-docs.yml
Update CI/CD flow to build docs on GitHub Pages and S3.
- The CI/CD pipeline has been updated to build documentation on GitHub Pages and upload it to S3.
- The workflow's name has been updated from *Update Docs on GitHub Pages* to *Update Docs on GitHub Pages and S3*.
- The AWS CLI command to copy files to the S3 bucket, `aws s3 cp docs/out ${{secrets.S3_BUCKET_PATH}}/ --recursive`, has been added to the *Copy files to specific path* job.
- Previously, the `cp -R docs/out/* ${{secrets.S3_BUCKET_PATH}}/` command was used to copy files, which is not as efficient or effective for working with S3 as the new `aws s3 cp` command.
- The changes do not provide a pull request description, but from the diff we can deduce that the intention is to update the CI/CD process to build documentation that …
=> 262 update ci cd flow to build docs at cloudcode ai domain

config.json, kaizen/llms/provider.py
Implemented a feature to pass and configure custom models.
- Added a new configuration section for a custom model named 'CUSTOM_MODEL' in the `config.json` file.
- The custom model configuration includes parameters for the model name, LiteLLM parameters like model, API key, and API base, and model info such as max tokens, input and output cost per token, max input and output tokens, LiteLLM provider, and mode.
- Updated the `kaizen/llms/provider.py` file to include a method `_register_unkown_models()`. This method is responsible for registering any unknown models defined in the configuration.
- Modified the `chat_completion()` function to use the custom model if it is provided, and to use the default model otherwise.
- Added a `model` parameter to the `available_tokens()` and …
=> fix: added way to pass and configure custom models

examples/code_review/main.py, kaizen/generator/pr_description.py, kaizen/helpers/output.py, kaizen/reviewer/code_review.py, pyproject.toml
This pull request fixes a bug in the usage calculation logic.
- Fixes an issue where the `review_data` variable was being incorrectly printed instead of `review_desc` in the `main.py` file.
- Updates the `_process_full_diff()` and `_reevaluate_response()` methods in the `pr_description.py` file to correctly update the `total_usage` dictionary with the usage information from the API responses.
- Removes the unnecessary `total_usage` parameter from the `_process_files()` method and its related methods, as the `total_usage` is now being tracked and updated within the `review_pull_request()` method.
- Bumps the version of the `kaizen-cloudcode` package from `0.3.3` to `0.3.4` in the `pyproject.toml` file.
<details> …
=> bugfix: usage calculation issue

kaizen/helpers/parser.py, kaizen/llms/prompts/code_review_prompts.py, kaizen/parsers/pythonparser.py, kaizen/reviewer/code_review.py
Adds a new function to extract code from markdown and refactors code review prompts.
- **New function:** `extract_code_from_markdown` in `kaizen/helpers/parser.py` extracts code snippets from markdown text.
- The `code_review_prompts.py` file has been updated to include new parameters for the `code_review` prompt:
- `start_line`: The starting line number of the code snippet in the pull request diff.
- `end_line`: The ending line number of the code snippet in the pull request diff.
- The `pythonparser.py` file now uses the `extract_code_from_markdown` function to format Python code snippets extracted from markdown.
- **Code review prompt updates:**
- The `code_review` prompt now includes instructions to replace the exact code changes between `start_line` and `end_line` …
=> 301 for code review code fix specify par of the code to be edited

kaizen/helpers/output.py, pyproject.toml
This pull request fixes an issue with incorrect tag formatting in the output markdown.
- **Issue:** The `PR_COLLAPSIBLE_TEMPLATE` in `kaizen/helpers/output.py` was incorrectly using a closing tag (`</strong>`) before the opening tag (`<strong>`).
- **Fix:** The closing tag was moved after the opening tag to ensure correct formatting.
- **Version Bump:** The version in `pyproject.toml` was updated to `0.3.8` to reflect the fix.
<details>
None
</details>
=> fix: tag issue in output markdown

examples/work_summarizer/main.py, kaizen/llms/prompts/work_summary_prompts.py, kaizen/reviewer/work_summarizer.py, pyproject.toml
This pull request updates the work summarizer to merge multiple summaries into a single consolidated summary.
- **Updated `work_summary_prompts.py`:**
- Added a new prompt `MERGE_WORK_SUMMARY_PROMPT` to merge multiple work summaries into a single summary.
- Modified the `details` field in the prompt to be a list of changes instead of a single string.
- **Updated `work_summarizer.py`:**
- Modified the `generate_work_summaries` function to use the `MERGE_WORK_SUMMARY_PROMPT` when multiple summaries are present.
- The function now uses `json.dumps` to convert the list of summaries into a JSON string for the prompt.
- **Updated `project.toml`:**
- Bumped the version to `0.3.10`.
<details>
None
</details>
=> fix: updated the work summary prompt to merge multiple summaries

config.json, examples/code_review/main.py, kaizen/helpers/parser.py, kaizen/llms/prompts/code_review_prompts.py, kaizen/reviewer/code_review.py, pyproject.toml, tests/helpers/test_patch_parser.py
This pull request updates the prompt used for pull request reviews based on a new method for passing pull request data.
- **Refactoring:** The `patch_to_separate_chunks` method in the `kaizen/helpers/parser.py` file has been replaced with `patch_to_combined_chunks`. This change likely aims to modify how code diffs are formatted and presented to the code review prompt.
- **New Feature:** The `file_name` field has been added to the JSON structure used for code review feedback. This allows for more precise identification of the file where issues are found.
- **Version Bump:** The `pyproject.toml` file has been updated to reflect the new version `0.3.11`.
- **Potential Impact:** The change in the prompt format might affect the code review feedback generated by the LLM. It's important to test …
=> 336 change the prompt for pr review based on new pr data passing method

kaizen/reviewer/code_review.py
This pull request addresses an issue where the code review process would not yield a response if there were no files to process. The change ensures that the review process continues to function correctly, even in the absence of file data.
- Removed the conditional check for `combined_diff_data` before yielding the processed file chunk, allowing the function to yield a response regardless of whether there are files to process.
- None explicitly introduced, but the change improves the robustness of the code review process.
- Simplified the logic in the `_process_files_generator` method by eliminating unnecessary conditional checks, enhancing readability and maintainability. …
=> fix: respond to code review even if now files to process

.github/workflows/ pypi-publish-cli.yml
This pull request modifies the GitHub Actions workflow for publishing to PyPI, specifically targeting the CLI package. The changes enhance the workflow by restricting tag patterns and adding support for manual triggers.
- Updated the tag pattern from `"*"` to `"cli-*"` to ensure that only tags prefixed with `cli-` trigger the publish workflow.
- Added a `workflow_dispatch` event to allow manual triggering of the workflow.
- Manual trigger support for the publish workflow, enabling developers to initiate the publish process without needing a tag push.
- No significant refactoring changes were made; however, the working directory specification remains consistent with the previous implementation.
> ✨ Generated with love by …
=> random changes

kaizen/generator/unit_test.py, kaizen/parsers/rustparser.py
This pull request introduces support for parsing Rust code to extract relevant information for unit test generation.
- Added a new `RustParser` class to the `parsers` module.
- Updated the `unit_test.py` file to include Rust as a supported language.
- **New Features:**
- The `RustParser` can now extract the following constructs from Rust code:
- `Module`
- `Struct`
- `Function`
- `Impl` block
- `Enum`
- No significant refactoring changes were made.
<details>
Changelog:
- Added code for parsing and extracting definitions from Rust code
- The `RustParser` class extracts the following constructs:
-  `Module`
- `Struct`
- `Function`
- `Impl` block
- `Enum` …
=> feat: Add parser support for Rust unit test generation

examples/unittest/rust.py
This pull request adds a new Rust example to the `examples/unittest` directory. The purpose is to demonstrate how to generate and run unit tests for Rust code using the `UnitTestGenerator` from the `kaizen.generator.unit_test` module.
- Key Changes:
- Added a new file `rust.py` in the `examples/unittest` directory
- Implemented a simple `Calculator` struct with `add`, `subtract`, and `get_result` methods
- Implemented a `greet` function that takes a name and returns a greeting
- Included the Rust code in the `code` variable and used the `UnitTestGenerator` to run the tests
- Provided an example of how to generate and run unit tests for Rust code using the `UnitTestGenerator`
- Refactoring:
- No major refactoring changes were made in this pull request
> ✨ Generated with …
=> chore: add Rust example for unit test runner

kaizen/actors/unit_test_runner.py
This pull request focuses on improving the organization of import statements within the `unit_test_runner.py` file by changing the import source of the `safe_path_join` function.
- Key Changes: Updated the import statement for `safe_path_join` from `kaizen.helpers.output` to `kaizen.helpers.general`.
- New Features: None.
- Refactoring: Simplified the import structure to enhance clarity and maintainability by ensuring that utility functions are sourced from a more appropriate module.
<details>
</details>
=> fix: safe path import

kaizen/generator/pr_description.py, kaizen/llms/prompts/pr_desc_prompts.py, kaizen/reviewer/code_review.py
This pull request focuses on refactoring the code for the PR description generator in the Kaizen project. The main goal is to improve the readability, maintainability, and performance of the PR description generation process.
- Removed unnecessary placeholders (`{PULL_REQUEST_TITLE}` and `{PULL_REQUEST_DESC}`) from the prompts used in the PR description generation process.
- Simplified the prompt formatting by removing the redundant title and description information, as this information is already available in the context of the pull request.
- Consolidated the prompt formatting into a single location (`pr_desc_prompts.py`) to improve code organization and maintainability.
- Refactored the `_process_file_chunk` method in the `_process_files_generator` function to remove the redundant …
=> fix: bug in desc generation

.experiments/code_review/main.py, config.json, kaizen/formatters/code_review_formatter.py, kaizen/llms/prompts/code_review_prompts.py
This pull request introduces the ability to select different models for code review and refines the code review format for better clarity.
- Added model selection to the `process_pr` function, allowing users to specify the desired model for code review.
- Updated the `config.json` file to include model information for the "best" model.
- Modified the `code_review_formatter.py` to improve the presentation of review results, separating critical issues from refinement suggestions and providing a more concise format for minor notes.
- **New Features:**
- None
- Refactored the `code_review_formatter.py` to improve the organization and readability of the code review output.
<details> …
=> feat updated pr review output format

.experiments/code_review/evaluate.py, .experiments/code_review/main.py, examples/code_review/main.py, kaizen/reviewer/code_review.py
This pull request aims to enhance the code review functionality of the Kaizen system. It introduces several key changes and new features to improve the quality and effectiveness of the code review process.
- Key Changes:
- Implemented a new filtering mechanism to only consider code review issues with a severity level of 5 or higher and a negative sentiment.
- Removed the `user` parameter from the `process_pr` function, as it was not being used.
- Refactored the `_process_files_generator` function to accept a new `custom_context` parameter, which can be used to pass additional context information to the code review process.
- Added the ability to re-evaluate the code review response, which can be useful for updating the feedback based on changes made to the pull request.
- …
=> feat: updated extra context issue

.github/workflows/kaizen-tests.yml, kaizen/generator/unit_test.py, kaizen/helpers/output.py, kaizen/helpers/parser.py, kaizen/llms/prompts/code_review_prompts.py, poetry.lock, pyproject.toml
- **Purpose:**
Update the GitHub Actions workflow to improve the Kaizen unit test runner.
- Removed the `continue-on-error` flag from the Kaizen unit test runner step.
- Improved the output formatting for writing test files.
- **Impact:**
The changes should ensure that the unit test workflow fails if any tests fail, providing clearer feedback on test results.
<details>
</details>
=> feat: updated the parser format

examples/code_review/main.py, kaizen/generator/pr_description.py, kaizen/llms/prompts/pr_desc_prompts.py
- **Purpose:**
Add a new feature to generate a Git commit message based on a PR description.
- Introduced a new `generate_pr_commit_message` method in the `PRDescriptionGenerator` class.
- Added a new prompt template `PR_COMMIT_MESSAGE_PROMPT` to generate the commit message based on the provided PR description.
- The generated commit message follows the Conventional Commits format and best practices.
- **Impact:**
This change will allow users to automatically generate a well-formatted and informative Git commit message when creating a new pull request, improving the overall quality and consistency of the codebase.
<details>
</details>
=> feat: kaizen generate pr commit msg and description

cli/kaizen_cli/cli.py, cli/kaizen_cli/commands/config_commands.py, cli/kaizen_cli/commands/reviewer_commands.py, cli/kaizen_cli/commands/unit_test_commands.py, cli/kaizen_cli/config/default_config.py, cli/kaizen_cli/config/manager.py, cli/kaizen_cli/utils.py, cli/poetry.lock, cli/pyproject.toml
- **Purpose:**
Refactor the CLI codebase and introduce a more robust configuration management system.
- Separated CLI commands into dedicated modules (config, unit_test, reviewer).
- Implemented a new configuration management system with support for nested configurations, environment variables, and persistent storage.
- Added commands for managing language models and Kaizen API keys in the configuration.
- Improved the unit test generation and execution commands.
- **Impact:**
The changes will improve the maintainability and extensibility of the CLI, making it easier to manage configurations and add new features in the future.
<details>
</details>
=> feat: updated the kaizen cli setup and functionality

kaizen/retriever/llama_index_retriever.py, pyproject.toml
- **Purpose:**
Reduce the embedding usage in the LLaMA Index Retriever to improve performance.
- Set the initial `embedding_usage` values for `prompt_tokens` and `total_tokens` to 0.
- Update the return value of the `setup_repository` method to include the updated `embedding_usage` instead of the `embed_model`.
- **Impact:**
The changes will reduce the memory and computational resources required by the LLaMA Index Retriever, potentially improving the overall performance of the system.
<details>
</details>
=> 549 kaizen cli make easy setup with ollama

docs/theme.config.jsx
- **Purpose:**
Change the footer copyright license from AGPL to MIT.
- Updated the footer copyright text to use the MIT license instead of AGPL.
- Removed the trailing newline at the end of the file.
- **Impact:**
This change will update the licensing information displayed in the website footer.
<details>
</details>
=> Updating license to MIT in docs

cli/kaizen_cli/commands/config_commands.py, cli/kaizen_cli/hooks/prepare-commit-msg, cli/pyproject.toml, kaizen/utils/config.py
- **Purpose:**
Modify the `add_model` command in the CLI to make the API key and base URL optional.
- Changed the `--api-key` and `--api-base` options in the `add_model` command to be optional, with default values of `None`.
- Updated the `prepare-commit-msg` hook to handle cases where the `generate-commit-msg` command fails or produces empty output.
- Bumped the CLI version to `0.2.4` in the `pyproject.toml` file.
- Added a default model configuration to the `config.py` file.
- **Impact:**
This change will allow users to add models to the configuration without providing an API key or base URL, making the CLI more flexible and easier to use.
<details>
</details>
=> feat: enhance commit message generation hook

cli/poetry.lock, cli/pyproject.toml
- **Purpose:**
Update the kaizen-cloudcode dependency to the latest version.
- Bump kaizen-cloudcode version from 0.4.12 to 0.4.14
- Update the poetry.lock file to reflect the new dependency version
- **Impact:**
This change will provide the latest features and bug fixes from the kaizen-cloudcode library, improving the overall functionality and reliability of the CLI application.
<details>
</details>
=> chore: update kaizen dependencies

cli/kaizen_cli/commands/config_commands.py, cli/pyproject.toml, kaizen/llms/provider.py, kaizen/utils/config.py, pyproject.toml
- **Purpose:**
Add support for configuring the API base URL for LiteLLM models in the Kaizen CLI.
- Added a new `--api-base` option to the `add_model` command in `config_commands.py`.
- Updated the `ConfigData` class in `config.py` to search for the configuration file in both the local directory and the user's home directory.
- Bumped the version of the `kaizen-cli` package to `0.2.6`.
- **Impact:**
This change allows users to specify the API base URL for their LiteLLM models, providing more flexibility in configuring the Kaizen CLI to work with different hosting environments.
<details>
</details>
=> feat: enhance model configuration handling

docs/pages/index.mdx
- **Purpose:**
Revise the homepage content and navigation to better highlight the Kaizen SDK and its key features.
- Renamed "API Reference" section to "SDK Reference" to align with the product branding.
- Updated the SDK Reference link to point to the "code_review" page within the SDK reference documentation.
- Adjusted the section descriptions to focus on the Kaizen SDK and its capabilities.
- **Impact:**
These changes will help users quickly navigate to the SDK documentation and understand the core functionality of the Kaizen product.
<details>
None
</details>
=> Update index.mdx Rename API -> SDK

docs/next.config.js
- **Purpose:**
Simplify the Next.js configuration for the documentation site.
- Removed the `basePath` and `assetPrefix` settings, which were previously set to `/kaizen/docs`.
- Enabled `unoptimized` images to avoid potential issues with image optimization.
- **Impact:**
This change will make the documentation site more straightforward to deploy and maintain, as it no longer requires a specific base path or asset prefix.
<details>
None
</details>
=> udpated the doc path

examples/api_test/api-main.py, kaizen/actors/api_test_runner.py, kaizen/generator/api_test.py, kaizen/generator/code_fixer.py, kaizen/generator/e2e_tests.py, kaizen/generator/pr_description.py, kaizen/reviewer/code_review.py
- **Purpose:**
Improve code readability and maintainability through formatting and minor refactoring.
- Standardized string formatting in file operations.
- Enhanced logging for error handling in test generation.
- Improved readability of loop structures and function calls.
- Removed unnecessary blank lines for cleaner code.
- Updated the code review prompt to include custom rules.
- **Impact:**
These changes enhance code clarity and maintainability, making future modifications easier and reducing potential errors.
<details>
None
</details>
=> Add styling checks

examples/code_review/main.py, kaizen/formatters/code_review_formatter.py, kaizen/generator/pr_description.py, kaizen/llms/prompts/code_review_prompts.py, kaizen/llms/provider.py, kaizen/reviewer/code_review.py
- **Purpose:**
Enhance the code review process by improving the formatting and categorization of issues.
- Implemented a scoring system to categorize issues as "critical", "important", or "can ignore" based on various factors like impact, severity, and issue type.
- Introduced a `filter_and_categorize_issues` function to filter out certain issue types and assign appropriate impact levels to the remaining issues.
- Updated the `create_pr_review_text` function to generate a more concise and actionable review summary.
- Added support for custom rules in the code review process, allowing the reviewer to specify additional guidelines.
- **Impact:**
The changes will result in more focused and impactful code reviews, helping developers quickly identify and address the most …
=> Updated styling ruleset

extensions/src/SidebarProvider.ts, extensions/src/apiRequest/apiRequestProvider.ts, extensions/src/apiRequest/apiRequestView.ts, extensions/src/utils/httpClient.ts
- **Purpose:**
Improve logging and streamline API request handling in the Sidebar and API Request components.
- Added console logs for better traceability in SidebarProvider and ApiRequestProvider.
- Removed commented-out code for clarity and maintainability.
- Ensured consistent initialization of the ApiRequestView.
- Simplified the logic for showing the API request view.
- Enhanced error handling for saving endpoints in HttpClient.
- **Impact:**
These changes enhance debugging capabilities and improve code readability, making future maintenance easier.
<details>
None
</details>
=> [WIP][feature][extension]  Multiple new requests

kaizen/tests/actions/diff_pr_test.py
- **Purpose:**
Improve input validation for GitHub PR requests.
- Added a Pydantic model `PRRequestModel` to validate owner, repo, and PR number inputs.
- Implemented a `validate_pr_request` wrapper function to validate the inputs.
- Updated `get_pr_info` and `get_pr_files` functions to use the validated data.
- **Impact:**
Ensures that the provided inputs for owner, repo, and PR number are valid, reducing the risk of errors and improving the overall robustness of the code.
<details>
- ****Purpose:**
**
Improve input validation for pull request data using Pydantic.
- ****Key Changes:****
- Introduced `PRRequestModel` for structured input validation.
- Added …
=> Input Validation for API URL
